/**
 * Task Module - Async task management for Agent
 *
 * Provides task scheduling, persistence, recovery, and concurrency control.
 */

export {
  TaskManager,
  type TaskManagerOptions,
  type TaskTerminalEvent,
  type TaskTerminalCallback,
  type TaskTerminalSubscriptionOptions,
  type ConcurrencyConfig,
  type ICreationProjectedTaskStore,
  type IRuntimeTaskManager,
} from './task-manager';
export {
  createTaskManagerCreationTaskProjection,
  type ICreationTaskProjection,
  type ICreationTaskProjectionStore,
  type CreationTaskProjectionConfig,
} from './creation-task-projection';
export {
  getCreationProjectedTaskRunId,
  isCreationProjectedTaskPayload,
  toSerializableCreationProjectedTask,
  toCreationProjectedTaskPayload,
  type CreationProjectedTaskArtifactBinding,
  type CreationProjectedTaskBinding,
  type CreationProjectedTaskPayload,
  type CreationProjectedTaskUpsertInput,
} from './creation-projected-task';
export {
  buildCancelTaskActionPlan,
  buildClearCompletedTaskPlan,
  buildRemoveTaskActionPlan,
  buildRetryTaskActionPlan,
  buildTaskResultOpenPlan,
  buildViewTaskResultActionPlan,
  type CancelTaskActionPlan,
  type ClearCompletedTaskPlan,
  type RemoveTaskPlan,
  type RetryTaskPlan,
  type TaskActionRejectPlan,
  type TaskActionNoopPlan,
  type TaskActionRejectReason,
  type TaskMediaCandidate,
  type TaskResultOpenPlan,
  type ViewTaskResultPlan,
} from './task-action-plan';
export {
  runCancelTaskRuntime,
  runClearCompletedTasksRuntime,
  runRemoveTaskRuntime,
  runRetryTaskRuntime,
  runSendTasksRuntime,
  runViewTaskResultRuntime,
  type ConversationTasksRuntimeInput,
  type TaskRuntimeAction,
  type TaskRuntimeDeps,
  type TaskRuntimeEffects,
  type TaskRuntimeInput,
  type TaskRuntimeHostPrivateLeaseGuard,
  type TaskRuntimeMediaGateway,
  type TaskRuntimeMessage,
  type TaskRuntimeResult,
  type TaskRuntimeTaskManager,
} from './task-runtime';
export {
  buildBackgroundTaskFailureUpdateView,
  createBackgroundTaskViewFromToolResultData,
  filterTasksForConversation,
  getTaskConversationId,
  getTaskResultUrl,
  matchesTaskConversation,
  mergeBackgroundTaskProgressView,
  toBackgroundTaskView,
  toBackgroundTaskViewStatus,
  toBackgroundTaskViewType,
  type BackgroundTaskView,
  type BackgroundTaskProgressPatch,
  type BackgroundTaskFailureUpdateOptions,
  type BackgroundTaskToolResultProjectionOptions,
  type BackgroundTaskViewStatus,
  type BackgroundTaskViewType,
} from './task-view-projector';
export {
  DEFAULT_AGENT_TASK_RESULT_DELIVERY_POLICY,
  AgentTaskResultObservationError,
  createAgentTaskResultEvidenceId,
  createAgentTaskResultFollowUpRequestId,
  createAgentTaskResultObservationId,
  createAgentTaskResultObservationRecords,
  evaluateAgentTaskResultDelivery,
  getAgentTaskResultDeliveryPolicy,
  isAgentTaskResultTerminalStatus,
  normalizeAgentTaskResultDeliveryPolicy,
  normalizeAgentTaskResultObservation,
  normalizeAgentTaskResultRefs,
  type AgentTaskResultDeliveryDecision,
  type AgentTaskResultObservationDiagnosticCode,
  type AgentTaskResultObservationRecords,
  type NormalizeAgentTaskResultObservationInput,
} from './task-result-observation';
export {
  AgentTaskResultObservationCoordinator,
  createAgentTaskResultObservationCoordinator,
  type AgentTaskResultFollowUpScheduler,
  type AgentTaskResultObservationCoordinatorDiagnostic,
  type AgentTaskResultObservationCoordinatorDiagnosticCode,
  type AgentTaskResultObservationCoordinatorOptions,
  type AgentTaskResultObservationRecordPort,
  type HandleAgentTaskResultTerminalInput,
  type HandleAgentTaskResultTerminalResult,
} from './task-result-observation-coordinator';
export {
  AgentTaskResultObservationRuntime,
  createAgentTaskResultObservationRuntime,
  type AgentTaskResultObservationContinuationPort,
  type AgentTaskResultObservationJournalPort,
  type AgentTaskResultObservationRuntimeAgentPort,
  type AgentTaskResultObservationRuntimeAgentRegistry,
  type AgentTaskResultObservationRuntimeOptions,
  type AgentTaskResultObservationRuntimeTaskPort,
  type AgentTaskResultObservationRuntimeTaskManagerTerminalInput,
  type AgentTaskResultObservationTerminalOptions,
} from './task-result-observation-runtime';
export {
  MemoryTaskStorage,
  FileTaskStorage,
  FileTaskStorageLoadError,
  StateTaskStorage,
  WorkspaceVisibleAgentTaskStorage,
  createFileTaskStorage,
  createFileWorkspaceVisibleAgentTaskStorage,
  createStateTaskStorage,
  getWorkspaceVisibleAgentTaskRecordsFilePath,
  type FileTaskStorageOptions,
  type StateTaskStorageAdapter,
  type StateTaskStorageOptions,
  type WorkspaceVisibleAgentTaskStorageOptions,
} from './task-storage';
export {
  CLEANUP_TASK_STATUSES,
  DEFAULT_TASK_CLEANUP_INTERVAL_MS,
  DEFAULT_TASK_RETENTION_PERIOD_MS,
  DEFAULT_TASK_STORAGE_KEY,
  RECOVERABLE_TASK_STATUSES,
  buildTaskStorageCleanupPlan,
  buildAgentTaskHostPrivateLeaseDiagnostic,
  createAgentTaskHostPrivateLease,
  createWorkspaceVisibleAgentTaskRecord,
  filterRecoverableTasks,
  isRecoverableTask,
  isRecoverableTaskStatus,
  isTaskCleanupCandidate,
  isTaskCleanupStatus,
  type AgentTaskHostPrivateLease,
  type AgentTaskHostSurface,
  type AgentTaskLeaseControl,
  type AgentTaskLeaseDiagnostic,
  type AgentTaskStorageScope,
  type TaskStorageCleanupPlan,
  type WorkspaceVisibleAgentTaskRecord,
} from './task-storage-policy';
export {
  MemoryTaskRecoveryStorage,
  FileTaskRecoveryStorage,
  StateTaskRecoveryStorage,
  createFileRecoveryStorage,
  createStateTaskRecoveryStorage,
  type FileTaskRecoveryStorageOptions,
  type StateTaskRecoveryStorageAdapter,
  type StateTaskRecoveryStorageOptions,
} from './task-recovery-storage';

// Re-export types from shared for convenience
export type {
  Task,
  TaskType,
  TaskStatus,
  TaskInput,
  TaskOutput,
  TaskProgressCallback,
  ITaskManager,
  ITaskStorage,
  ITaskRecoveryStorage,
  TaskRecoveryInfo,
  SerializableTask,
  TaskExecutor,
  TaskExecutionContext,
  TaskLifecycleMetadata,
  TaskRunLease,
  AgentTaskResultDeliveryPolicy,
  AgentTaskResultFollowUpRequest,
  AgentTaskResultObservation,
  AgentTaskResultRef,
  AgentTaskResultRefKind,
  AgentTaskResultSource,
  AgentTaskResultTerminalStatus,
  TaskCostPhase,
  TaskInterruptPolicy,
  TaskRecoverPolicy,
  TaskRunMode,
} from '@neko/shared';
