packages:
  - packages/*
  - packages/neko-agent/packages/*
  - packages/neko-assets/packages/*
  - packages/neko-canvas/packages/*
  - packages/neko-cut/packages/*
  - packages/neko-engine/packages/*
  - packages/neko-preview/packages/*
  - packages/neko-story/packages/*
  - packages/neko-tools/packages/*

ignoredBuiltDependencies:
  - esbuild
  - sharp
