packages:
  - packages/*
  - packages/neko-audio/packages/*
  - packages/neko-agent/packages/*
  - packages/neko-assets/packages/*
  - packages/neko-canvas/packages/*
  - packages/neko-cut/packages/*
  - packages/neko-engine/packages/*
  - packages/neko-live/packages/*
  - packages/neko-model/packages/*
  - packages/neko-preview/packages/*
  - packages/neko-sketch/packages/*
  - packages/neko-puppet/packages/*
  - packages/neko-story/packages/*
  - packages/neko-tools/packages/*
  - packages/neko-market/packages/*
  - packages/neko-auth/packages/*

shamefullyHoist: true
publicHoistPattern:
  - '*react-markdown*'
  - '*remark*'
  - '*unified*'
  - '*prism*'

ignoredBuiltDependencies:
  - esbuild
  - sharp
