[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/Inochi2D/inox2d"]
git = "https://github.com/Inochi2D/inox2d"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
