import { createHash } from 'node:crypto';
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  CANVAS_GENERATED_DRAFT_CANDIDATE_ID_PREFIX,
  CANVAS_GENERATED_DRAFT_GROUP_CONTRACT_VERSION,
  CANVAS_GENERATED_DRAFT_GROUP_ID_PREFIX,
  type NekoAssetsGeneratedCandidatePromotionInput,
  type NekoAssetsGeneratedCandidateSource,
} from '@neko/shared';
import { GeneratedCandidatePromotionService } from './GeneratedCandidatePromotionService';

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    temporaryDirectories
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

describe('GeneratedCandidatePromotionService', () => {
  it('materializes generated bytes under AssetLibrary ownership and replays idempotently', async () => {
    const fixture = await createFixture('candidate bytes');
    const registerAsset = vi.fn(async ({ filePath }: { filePath: string }) => ({
      entityId: 'asset:entity:1',
      variantId: 'asset:variant:1',
      fileId: 'asset:file:1',
      path: toPortableAssetPath(fixture.root, filePath),
      mediaType: 'image' as const,
    }));
    const service = createService(fixture.root, registerAsset);
    const input = promotionInput([fixture.source]);

    const first = await service.promote(input);
    const replayed = await service.promote(input);

    expect(first.status).toBe('saved');
    expect(replayed).toEqual(first);
    expect(registerAsset).toHaveBeenCalledTimes(1);
    const registeredPath = registerAsset.mock.calls[0]?.[0].filePath;
    if (!registeredPath) throw new Error('Expected Asset registration path.');
    expect(registeredPath).toContain(path.join('neko', 'assets', 'files', 'image'));
    await expect(readFile(registeredPath, 'utf8')).resolves.toBe('candidate bytes');
    expect(registeredPath).not.toContain(path.join('neko', 'generated'));
    expect(registeredPath).not.toContain(path.join('.neko', '.cache'));
  });

  it('returns per-candidate partial failure and retries only unresolved work', async () => {
    const fixture = await createFixture('candidate bytes');
    const secondCandidateId = `${CANVAS_GENERATED_DRAFT_CANDIDATE_ID_PREFIX}output:2`;
    const registerAsset = vi.fn(async ({ filePath }: { filePath: string }) => ({
      entityId: 'asset:entity:1',
      variantId: 'asset:variant:1',
      fileId: 'asset:file:1',
      path: toPortableAssetPath(fixture.root, filePath),
      mediaType: 'image' as const,
    }));
    const service = createService(fixture.root, registerAsset);
    const first = await service.promote({
      ...promotionInput([fixture.source]),
      request: {
        ...promotionInput([fixture.source]).request,
        selections: [
          promotionInput([fixture.source]).request.selections[0]!,
          {
            candidateId: secondCandidateId,
            revision: 'revision:2',
            contentDigest: 'sha256:missing',
          },
        ],
      },
    });

    expect(first.status).toBe('partial');
    expect(first.items.map((item) => item.status)).toEqual(['saved', 'failed']);
    expect(first.items[1]).toMatchObject({
      candidateId: secondCandidateId,
      diagnostic: { code: 'source-unavailable' },
    });

    const secondPath = path.join(fixture.root, '.neko', '.cache', 'generated', 'second.png');
    await mkdir(path.dirname(secondPath), { recursive: true });
    await writeFile(secondPath, 'second bytes');
    const secondSource = generatedSource(
      secondCandidateId,
      secondPath,
      'second bytes',
      'revision:2',
    );
    const retry = await service.promote(promotionInput([secondSource], 'promotion:retry'));

    expect(retry.status).toBe('saved');
    expect(registerAsset).toHaveBeenCalledTimes(2);
  });

  it('fails visibly when revision evidence or source bytes changed', async () => {
    const fixture = await createFixture('candidate bytes');
    const registerAsset = vi.fn();
    const service = createService(fixture.root, registerAsset);
    const baseInput = promotionInput([fixture.source]);
    const staleRevision: NekoAssetsGeneratedCandidatePromotionInput = {
      ...baseInput,
      request: {
        ...baseInput.request,
        selections: baseInput.request.selections.map((selection) => ({
          ...selection,
          revision: 'revision:stale',
        })),
      },
    };

    const revisionResult = await service.promote(staleRevision);
    expect(revisionResult).toMatchObject({
      status: 'failed',
      items: [{ diagnostic: { code: 'content-changed' } }],
    });

    await writeFile(fixture.source.sourcePath, 'changed bytes');
    const digestResult = await service.promote(
      promotionInput([fixture.source], 'promotion:digest'),
    );
    expect(digestResult).toMatchObject({
      status: 'failed',
      items: [{ diagnostic: { code: 'content-changed' } }],
    });
    expect(registerAsset).not.toHaveBeenCalled();
  });
});

async function createFixture(content: string): Promise<{
  root: string;
  source: NekoAssetsGeneratedCandidateSource;
}> {
  const root = await mkdtemp(path.join(tmpdir(), 'neko-generated-promotion-'));
  temporaryDirectories.push(root);
  const sourcePath = path.join(root, '.neko', '.cache', 'generated', 'candidate.png');
  await mkdir(path.dirname(sourcePath), { recursive: true });
  await writeFile(sourcePath, content);
  await access(sourcePath);
  return {
    root,
    source: generatedSource(
      `${CANVAS_GENERATED_DRAFT_CANDIDATE_ID_PREFIX}output:1`,
      sourcePath,
      content,
      'revision:1',
    ),
  };
}

function generatedSource(
  candidateId: string,
  sourcePath: string,
  content: string,
  revision: string,
): NekoAssetsGeneratedCandidateSource {
  return {
    candidateId,
    title: 'Concept Candidate',
    mediaKind: 'image',
    mimeType: 'image/png',
    revision,
    contentDigest: hash(content),
    sourcePath,
    taskId: 'task:1',
    runId: 'run:1',
    provider: 'test-provider',
    prompt: 'A concept image',
  };
}

function promotionInput(
  sources: readonly NekoAssetsGeneratedCandidateSource[],
  requestId = 'promotion:1',
): NekoAssetsGeneratedCandidatePromotionInput {
  return {
    request: {
      version: CANVAS_GENERATED_DRAFT_GROUP_CONTRACT_VERSION,
      requestId,
      projectionId: `${CANVAS_GENERATED_DRAFT_GROUP_ID_PREFIX}task:1`,
      target: {
        documentRef: { kind: 'workspace-path', path: 'neko/boards/concept.nkc' },
        documentId: 'document:1',
        canvasId: 'canvas:1',
        revision: 'canvas-revision:1',
        conversationId: 'conversation:1',
        taskId: 'task:1',
        resolutionSource: 'conversation',
        frozenAt: '2026-07-15T00:00:00.000Z',
      },
      selections: sources.map((source) => ({
        candidateId: source.candidateId,
        revision: source.revision,
        contentDigest: source.contentDigest,
      })),
      requestedAt: '2026-07-15T00:01:00.000Z',
    },
    sources,
  };
}

function createService(
  root: string,
  registerAsset: ConstructorParameters<
    typeof GeneratedCandidatePromotionService
  >[0]['registerAsset'],
): GeneratedCandidatePromotionService {
  return new GeneratedCandidatePromotionService({
    assetFilesRoot: path.join(root, 'neko', 'assets', 'files'),
    fs: {
      readFile,
      writeFile,
      createDirectory: (directory) => mkdir(directory, { recursive: true }),
      exists: async (filePath) => {
        try {
          await access(filePath);
          return true;
        } catch {
          return false;
        }
      },
    },
    registerAsset,
  });
}

function hash(content: string): string {
  return `sha256:${createHash('sha256').update(content).digest('hex')}`;
}

function toPortableAssetPath(root: string, filePath: string): string {
  return path.relative(root, filePath).replace(/\\/g, '/');
}
