/**
 * @neko/agent - Agent Application Package
 *
 * This package provides the agent runtime for AI-powered task execution.
 * It can run standalone (without platform) or integrated with platform.
 *
 * Standalone mode:
 * - Uses built-in LLM client
 * - Full MCP support
 * - Skill system
 *
 * Integrated mode:
 * - Uses platform's LLM routing
 * - Media generation via platform
 * - Workflow execution via platform
 */

// Re-export shared types for convenience
export type {
  // Agent types
  AgentState,
  AgentConfig,
  AgentContext,
  AgentStep,
  AgentResult,
  AgentCheckpoint,
  IAgentExecutor,
  IAgentRuntime,
  // Hook types
  ExecutorHooks,
  ToolCallInfo,
  ToolResultWithMeta,
  ThinkContext,
  // Skill types (from shared - Claude-compatible)
  Skill,
  SlashCommand,
  SkillMatch,
  SkillSource,
  SkillInjection,
  ISkillService,
  ISkillRegistry,
  ISkillMatcher,
  ISkillInjector,
  SkillFrontmatter,
  CommandFrontmatter,
  ParsedSkillFile,
  SkillLoadResult,
  SkillLoadError,
  ISkillFileSystem,
  SkillSummary,
  SkillValidationResult,
  // MCP types
  IMCPManager,
  IMCPClient,
  MCPServerConfig,
  MCPToolDefinition,
  MCPToolResult,
  MCPResource,
  MCPPrompt,
  // Tool types
  IToolRegistry,
  Tool,
  ToolResult,
  ToolCategory,
  ToolCallRequest,
  // Platform types (for integration)
  IPlatform,
  IService,
  ChatMessage,
  ServiceResponse,
  StreamChunk,
  ServiceOptions,
  ToolDefinition,
  LLMProviderConfig,
} from '@neko/shared';

export {
  ExperimentRunner,
  applyAblationToggles,
  extractAblationMarker,
  MetricsHooks,
  buildComparison,
  formatComparisonMarkdown,
  BASELINE,
  NO_COMPRESSION,
  NO_CREATIVE_COMPRESSION,
  NO_SKILL_DISCOVERY,
  NO_SKILL_INJECTION,
  NO_DYNAMIC_TOOLSETS,
  NO_VALIDATION,
  NO_RETRY,
  NO_SETTINGS_HOOKS,
  NO_PROJECT_MEMORY,
  NO_COMPACT_LOGGING,
  NO_AUTO_MEMORY_EXTRACTION,
  NO_MEMORY_RECALL,
  NO_TRAITS,
  NO_THINKING,
  ALWAYS_ONLY_TOOLS,
  PLAN_PERMISSION_MODE,
  ASK_PERMISSION_MODE,
  SINGLE_ITERATION,
  NO_ALL_COMPRESSION,
  NO_ALL_SKILLS,
  NO_ALL_EXTERNAL,
  MINIMAL,
  createStandardAblationSuite,
  createGroupAblationSuite,
  createParameterAblationSuite,
} from './experiment';
export type {
  AblationToggles,
  AblationMarkerHook,
  EvaluationResult,
  ExperimentEvaluator,
  ExperimentIsolationMode,
  ExperimentConfig,
  ExperimentOutputFile,
  ExperimentOutputWriter,
  ExperimentRunDescriptor,
  ExperimentRunIsolation,
  ExperimentVariant,
  IExperimentSession,
  ISessionFactory,
  TokenMetrics,
  ToolCallMetric,
  TurnMetrics,
  ExperimentMetrics,
  VariantRunResult,
  VariantResult,
  ExperimentResult,
  ComparisonEntry,
  ExperimentProgressEvent,
} from './experiment';

export {
  parseProviderCardMarkdown,
  ProviderCardRegistry,
  createProviderCardRegistry,
  ProviderRouter,
  createProviderRouter,
  loadProviderCardDirectory,
  registerProviderCardDirectory,
  registerRuntimeProviderCardDirectories,
  type ParseProviderCardOptions,
  type LoadProviderCardDirectoryOptions,
  type RegisterProviderCardDirectoryOptions,
  type ProviderCardLoaderFs,
  type ProviderCardDirent,
  type ProviderCardLoadError,
  type ProviderCardRuntimeLogger,
  type RegisterRuntimeProviderCardDirectoriesOptions,
  type RuntimeProviderCardDirectoryRegistrationResult,
  createProviderExpressionPromptFragments,
  type ProviderExpressionContextOptions,
} from './provider';

export {
  AgentProfileRegistry,
  ArtifactProfileRegistry,
  CreationProfileRegistry,
  ProviderExpressionProfileRegistry,
  createArtifactProfileRegistry,
  createCreationProfileRegistry,
  createProviderExpressionProfileRegistry,
  BUILTIN_ARTIFACT_PROFILES,
  BUILTIN_CREATION_PROFILES,
  IDC_DEFAULT_CREATION_PROFILE,
  type AgentProfileDescriptor,
  type AgentProfileRegistryOptions,
} from './profile';

export {
  PERCEPTION_AUDIO_TRANSCRIBE_METADATA,
  PERCEPTION_IMAGE_SIMILARITY_METADATA,
  PERCEPTION_IMAGE_CLASSIFY_METADATA,
  PERCEPTION_DESCRIBE_INPUT_METADATA,
  PERCEPTION_VIDEO_DETECT_SHOTS_METADATA,
  PerceptionAudioTranscribeTool,
  PerceptionImageSimilarityTool,
  PerceptionImageClassifyTool,
  PerceptionDescribeInputTool,
  PerceptionVideoDetectShotsTool,
  createPerceptionTools,
  perceptionToolGroup,
  type PerceptionAudioTranscribeToolConfig,
  type PerceptionImageSimilarityToolConfig,
  type PerceptionImageClassifyToolConfig,
  type PerceptionToolMetadata,
  type PerceptionToolResult,
  type PerceptionClassifyClient,
  type PerceptionDetectShotsClient,
  type PerceptionSimilarityClient,
  type PerceptionTranscribeClient,
  BuiltinTool,
  createTool,
  ToolRegistry,
  createToolRegistry,
  ToolCategoryRegistry,
  createToolCategoryRegistry,
  ToolInjectionManager,
  createToolInjectionManager,
  // Core meta tools
  ActivateSkillTool,
  DeactivateSkillTool,
  CreateSkillTool,
  SetExecutionModeTool,
  GetContextTool,
  createCoreMetaTools,
  type ISkillProvider,
  type ExecutionModeActivationFailureCode,
  type ExecutionModeActivationResult,
  type SkillActivationProviderResult,
  type SkillDeactivationProviderResult,
  type SkillProviderFailureCode,
  type SkillProviderFactory,
  type SkillProviderMaybePromise,
  // Core file/system tools
  ReadTool,
  WriteTool,
  BashTool,
  type BashToolOptions,
  ListDirectoryTool,
  GrepTool,
  type GrepToolOptions,
  MemoryWriteTool,
  createCoreTools,
  type CoreToolsOptions,
  // Injection constants
  DEFAULT_INJECTION_CONFIG,
  CORE_TOOLS,
} from './tools';

// Export plan parsing and message projection helpers
export {
  buildPlanApprovalDispatchPlan,
  buildPlanApprovalExecutionDispatch,
  buildPlanApprovalExecutionOverrides,
  buildPlanApprovalExecutionMessage,
  buildPlanFileReadErrorMessage,
  buildPlanRejectionFeedbackMessage,
  buildPlanRejectionFeedbackStreamMessage,
  buildPlanStatusUpdateMessage,
  buildPromptModeChangedMessage,
  createPlanContentBlockFromToolResultData,
  parsePlanMarkdown,
  projectPlanStepActionReview,
  projectPlanStepModificationReview,
  runPlanApprovalRuntime,
  runPlanRejectionRuntime,
  runPlanStepActionRuntime,
  runPlanStepModificationRuntime,
  type Plan,
  type PlanApprovalDispatchPlan,
  type PlanApprovalDispatchPlanInput,
  type PlanApprovalExecutionDispatch,
  type PlanFileReadErrorMessage,
  type PlanApprovalRuntimeInput,
  type PlanApprovalRuntimeResult,
  type PlanStep,
  type PlanPromptMode,
  type PlanRejectionRuntimeInput,
  type PlanRejectionFeedbackStreamMessage,
  type PlanReviewDecision,
  type PlanReviewConversationStore,
  type PlanReviewRuntimeEffects,
  type PlanReviewRuntimeMessage,
  type PlanReviewRuntimeResult,
  type PlanStatusUpdateMessage,
  type PlanStepActionRuntimeInput,
  type PlanStepModificationRuntimeInput,
  type PlanStepReviewAction,
  type PlanStepReviewProjection,
  type PlanStepStatusUpdateMessage,
  type PlanToolResultProjection,
  type PlanToolResultProjectionOptions,
  type PromptModeChangedMessage,
} from './plan';

// Export logger
export { setRootLogger, getLogger as getAgentLogger } from './utils/logger';

// Export errors
export { AgentError, type AgentErrorCategory, type AgentErrorInfo } from './errors';

// Export executor
export { AgentExecutor, createAgentExecutor, type AgentExecutorOptions } from './executor';

// Export hooks
export {
  RetryHooks,
  MemoryHooks,
  composeHooks,
  createRetryHooks,
  createMemoryHooks,
  type RetryHooksOptions,
  type MemoryHooksOptions,
} from './hooks';

// Export memory
export { FileProjectMemoryManager, createFileProjectMemoryManager, MemoryRecall } from './memory';
export type { MemoryRecallOptions, RecalledMemory } from './memory';

// Export MCP
export {
  StdioMCPClient,
  HttpMCPClient,
  createMCPClient,
  MCPManager,
  MCPTool,
  connectMCPServersRuntime,
  createMcpToolCreationOptionsForExternalResearch,
  createMCPTools,
  createAllMCPTools,
  MCPTestService,
  getMCPTestService,
  type MCPToolCallManager,
  type MCPToolDiscoveryManager,
  type MCPRuntimeBootstrapLogger,
  type MCPRuntimeBootstrapOptions,
  type MCPRuntimeBootstrapResult,
  type MCPRuntimeConnectionFailure,
  type MCPRuntimeManager,
  type MCPRuntimeToolRegistry,
  type MCPTestConfig,
  type MCPTestResult,
} from './mcp';

// Export validation
export {
  // Types
  type ImageConstraints,
  type OutputConstraints,
  type ValidationHooksOptions,
  type ValidationError,
  type ValidationWarning,
  type ValidationResult,
  type ValidationErrorType,
  type ImageInfo,
  type MermaidValidationResult,
  type MermaidBlockInfo,
  type MermaidBlockValidationResult,
  type JsonBlockInfo,
  type JsonBlockValidationResult,
  type ValidationResultWithBlocks,
  // Constants
  DEFAULT_IMAGE_CONSTRAINTS,
  DEFAULT_OUTPUT_CONSTRAINTS,
  // Image Validator
  ImageValidator,
  ImageValidationError,
  createImageValidator,
  // Output Validator
  OutputValidator,
  createOutputValidator,
  // Validation Hooks
  ValidationHooks,
  createValidationHooks,
  // Extractors
  MermaidExtractor,
  JsonExtractor,
  createMermaidExtractor,
  createJsonExtractor,
  // Validators
  MermaidValidator,
  JsonSchemaValidator,
  LengthValidator,
  createMermaidValidator,
  createJsonSchemaValidator,
  createLengthValidator,
  // Checkers
  MermaidBlockChecker,
  createMermaidBlockChecker,
} from './validation';

// Export permission
export {
  // Types
  type PermissionMode,
  type PermissionDecision,
  type PermissionRules,
  type PermissionConfig,
  type PermissionCheckResult,
  type ToolConfirmationRequest,
  type ToolConfirmationResponse,
  type ConfirmToolCallback,
  type PlanFileResult,
  type PermissionHooksOptions,
  // Constants
  DEFAULT_READ_ONLY_TOOLS,
  READ_ONLY_MCP_PREFIXES,
  DEFAULT_PERMISSION_CONFIG,
  PLAN_MODE_SYSTEM_REMINDER,
  PLAN_FILE_PATH,
  // Rule Matcher
  PermissionRuleMatcher,
  createPermissionRuleMatcher,
  normalizeToolCall,
  matchesPattern,
  isInPatternList,
  isReadOnlyTool,
  isPlanFileWrite,
  // Permission Hooks
  PermissionHooks,
  createPermissionHooks,
  ToolTraitsRegistry,
  DEFAULT_CREATIVE_TOOL_TRAITS,
} from './permission';

// Export prompt file projection
export {
  DEFAULT_AGENTS_FILE_CONTENT,
  DEFAULT_NEW_PROMPT_NAME,
  PROMPT_FILE_EXTENSION,
  buildAgentsFileLoadPlan,
  buildAgentsFilePlan,
  buildPromptConfigFilePlan,
  buildPromptFileContent,
  parseCharacterRoleEvaluationReportOutput,
  projectCharacterDialogueSystemPrompt,
  projectCharacterRoleEvaluationPrompt,
  createPromptFileRuntime,
  ensurePromptFileExtension,
  extractPromptNameFromContent,
  generatePromptFileId,
  generatePromptFileName,
  projectPromptFileInfo,
  promptFileInfoToConfig,
  shouldScanPromptFile,
  syncPromptFilesWithConfig,
  type AgentsFileLoadCandidate,
  type CharacterDialogueProfilePromptOptions,
  type CharacterRoleEvaluationPromptProjection,
  type CharacterRoleEvaluationReportParseResult,
  type PromptFileInfo,
  type PromptFileScanResult,
  type PromptFileScanResult as AgentPromptFileScanResult,
  type AgentsFileFailurePlan,
  type AgentsFilePlan,
  type LoadedAgentsFile,
  type PromptFileRuntime,
  type PromptFileRuntimeFs,
  type PromptFileRuntimeLogger,
  type PromptFileRuntimeOptions,
  type PromptFileRuntimePath,
  type PromptFileRuntimeStatLike,
  type PromptFileSaveResult,
  type PromptConfigFilePlan,
  type SavePromptFileInput,
  PromptManager,
  createPromptManager,
  // System Prompt Builder
  SystemPromptBuilder,
  createSystemPromptBuilder,
  createConversationPromptModeRuntime,
  runSendConversationPromptModeRuntime,
  runSetConversationPromptModeRuntime,
  runToggleConversationPromptModeRuntime,
  runSystemPromptAgentsFileLoadRuntime,
  getDefaultPersonalPath,
  hasAgentsFile,
  BUILTIN_PROMPTS,
  BUILTIN_DEFAULT_PROMPT_EN,
  BUILTIN_DEFAULT_PROMPT_ZH,
  BUILTIN_PLAN_PROMPT_EN,
  BUILTIN_PLAN_PROMPT_ZH,
  type ISystemPromptBuilder,
  type SystemPromptBuilderConfig,
  type SystemPromptAgentsFileRuntimeDeps,
  type SystemPromptAgentsFileRuntimeInput,
  type ConversationPromptModeRuntime,
  type ConversationPromptModeRuntimeOptions,
  type ConversationPromptModeSnapshot,
  type PromptMode,
  type PromptLocale,
  type AgentsSource,
  type AgentsLoadResult,
  type BuiltinPromptKey,
  // Re-exported types from shared
  type Prompt,
  type PromptVariable,
  type PromptCategory,
  type RenderedPrompt,
  type IPromptManager,
} from './prompt';

// Export skill
export {
  // Core classes
  SkillRegistry,
  SkillLoader,
  createNodeSkillLoader,
  SkillInjector,
  SkillMatcher,
  KeywordSkillMatcher,
  createCommandBackedSkill,
  createLazyCommandBackedSkill,
  ToolGuard,
  NoOpToolGuard,
  createToolGuard,
  // Skill Service
  SkillService,
  createSkillService,
  // Activation-time subpackage guard (ADR §5.2.10)
  assertSubpackagesAvailable,
  SkillActivationError,
  type ISubpackageResolver,
  type SubpackageInfo,
  type SkillActivationIssue,
  type SkillActivationIssueCode,
  // ToolGroup Registry
  ToolGroupRegistry,
  createToolGroupRegistry,
  projectRuntimeToolGroup,
  projectRuntimeToolGroups,
  // Skill Conflict Resolver
  SkillConflictResolver,
  createSkillConflictResolver,
  SkillRegistryPopulator,
  // Path Matcher
  matchSkillPaths,
  globMatch,
  type SkillPathInfo,
  // Markdown Parser
  MarkdownParser,
  createMarkdownParser,
  // Types
  type IToolGuard,
  type ToolCallInput,
  type ToolGuardResult,
  type SkillDiscoveryResult,
  type SkillApplicationResult,
  type LazySkillRegistryPopulateInput,
  type LazySkillRegistryScanGroup,
  type LazySkillRegistryScanResult,
  type ConfirmSkillCallback as ConfirmSkillCallbackFn,
  type SkillServiceConfig,
  type LazySkill,
  type LazyCommand,
  type LazySkillLoadResult,
  type IMarkdownParser,
  type YamlValue,
  appendSkillFileScanLoadResult,
  buildSkillDirectoryLoadFailureResult,
  buildCommandFileCreationPlan,
  buildCommandFileDeletionPlan,
  buildCommandFileOpenPlan,
  buildSkillFileScanPlan,
  buildSkillFileCreationPlan,
  buildSkillDirectoryDeletionPlan,
  buildSkillDirectoryDuplicationPlan,
  createEmptySkillFileScanResult,
  buildSkillSupportFileOpenPlan,
  normalizeSkillFrontmatter,
  normalizeDuplicatedSkillContent,
  buildCommandFileContent,
  shouldCopySkillDirectoryEntry,
  buildSkillAwareSystemPrompt,
  buildRuntimeSkillAwareSystemPrompt,
  buildSkillInjectionMessage,
  buildSkillsListMessage,
  SKILL_FILE_WATCH_DEBOUNCE_MS,
  SKILL_PATH_TRIGGER_DEBOUNCE_MS,
  createSkillFileRuntime,
  createLegacySkillMigrationRuntime,
  LegacySkillMigrationError,
  createRuntimeSkillLazySync,
  ConversationSkillRuntime,
  SkillLifecycleRuntime,
  SkillLifecycleStore,
  buildLifecyclePromptSectionId,
  compareLifecycleRecords,
  createConversationSkillProvider,
  createRuntimeSkillBootstrap,
  defaultDeactivationPolicy,
  defaultSkillLifecycleRequest,
  getEnabledSkillPromptEntries,
  hasBlockingLifecycleProjectionDiagnostic,
  populateLazyRuntimeSkillRegistry,
  projectSkillLifecycle,
  projectSkillSummary,
  toSkillPromptEntries,
  toConfiguredSkillFileCatalog,
  resolveSkillPathTriggers,
  type ActiveSkillState,
  type ApplySkillInvocationInput,
  type ApplySlashSkillCommandInput,
  type ConversationSkillAgentBridge,
  type ConversationSkillProviderEffects,
  type ConversationSkillProviderOptions,
  type ConversationSkillRuntimeDeps,
  type ConversationSkillRuntimeLogger,
  type ExecuteSkillInput,
  type AutoActivateSkillInput,
  type SkillLifecycleCreateRecordInput,
  type SkillLifecycleExpireInput,
  type SkillLifecyclePreparedActivationInput,
  type SkillLifecycleProjectionInput,
  type SkillLifecycleRenewRecordInput,
  type SkillLifecycleRuntimeOptions,
  type SkillLifecycleStoreOptions,
  type SkillFileScanGroup,
  type SkillFileScanResult,
  type SkillFileScanResult as AgentSkillFileScanResult,
  type SkillFileScanGroupOf,
  type SkillFileScanResultOf,
  type LazySkillFileScanResult,
  type SkillInjectionMessage,
  type SkillsListMessage,
  type ConfiguredSkillFileCatalog,
  type BuildSkillAwareSystemPromptInput,
  type BuildRuntimeSkillAwareSystemPromptInput,
  type CommandFileCreationPlan,
  type CommandFileDeletionPlan,
  type CommandFileOpenPlan,
  type CreateCommandFileInput,
  type DeleteCommandFileInput,
  type DeleteSkillDirectoryInput,
  type DuplicateSkillDirectoryInput,
  type ResolveSkillPathTriggersOptions,
  type SkillFileLoadResultOf,
  type SkillFileRuntime,
  type SkillFileRuntimeDirentLike,
  type SkillFileRuntimeFs,
  type SkillFileRuntimeLoader,
  type SkillFileRuntimeLogger,
  type SkillFileRuntimeOptions,
  type SkillFileRuntimePath,
  type LegacySkillMigrationDirentLike,
  type LegacySkillMigrationFs,
  type LegacySkillMigrationPath,
  type LegacySkillMigrationRuntime,
  type LegacySkillMigrationRuntimeOptions,
  type SkillFileScanError,
  type SkillFileScanKind,
  type SkillFileScanPlan,
  type SkillFileScanPlanEntry,
  type SkillFileSource,
  type SkillDirectoryDeletionPlan,
  type SkillDirectoryDuplicationPlan,
  type SkillFileCreationPlan,
  type SkillFileOperationFailurePlan,
  type SkillPromptEntry,
  type PopulateLazyRuntimeSkillRegistryInput,
  type RuntimeSkillLazySync,
  type RuntimeSkillLazySyncLogger,
  type RuntimeSkillLazySyncOptions,
  type RuntimeSkillAwareSystemPromptResult,
  type RuntimeSkillBootstrap,
  type RuntimeSkillBootstrapLogger,
  type RuntimeSkillBootstrapOptions,
  type RuntimeSkillProviderState,
  type RuntimeToolGroupRegistryView,
  type SkillRegistryPopulateInput,
  type SkillRegistryPopulationSummary,
  type SkillRegistryScanGroup,
  type SkillRegistryScanResult,
  type SkillPathTriggerMatch,
  type SkillSupportFileOpenPlan,
  type SkillSupportFileOpenType,
} from './skill';

// Re-export skill utility functions from shared
export {
  toSkillSummary,
  validateSkill,
  createSkill,
  toCommandSummary,
  validateCommand,
  createCommand,
  parseAllowedTools,
  isToolAllowed,
  extractSupportFileRefs,
  SKILL_DIRECTORIES,
  COMMAND_DIRECTORIES,
} from '@neko/shared';

// Export context management
export {
  LayeredContextManager,
  createLayeredContextManager,
  ConversationCompressor,
  createConversationCompressor,
  ContextPersistenceManager,
  InMemoryContextStorage,
  createContextPersistenceManager,
  LLMSummarizer,
  createLLMSummarizer,
  DEFAULT_SUMMARIZER_CONFIG,
  type LLMSummarizerConfig,
} from './context';

// Export settings hook execution
export {
  type HookExecutionResult,
  type ISettingsFileSystem,
  type IShellExecutor,
  type LoadedSettingsHook,
  type SettingsHookLoadResult,
  type SettingsHookLoaderOptions,
  SettingsHookLoader,
  createSettingsHookLoader,
} from './hook-loader';

// Export subagent
export {
  // Types
  type SubAgentRunMode,
  type SubAgentStatus,
  type BuiltinSpecializedAgentType,
  type SpecializedAgentType,
  type ModelTier,
  type AgentToolPolicy,
  type SubAgentConfig,
  type SpecializedAgentPreset,
  type SubAgentResult,
  type SubAgentEventType,
  type SubAgentEvent,
  type SubAgentEventListener,
  type SubAgentManagerDeps,
  type SubAgentExecutor,
  type SubAgentCreateAgentContext,
  type SubAgentSkillContentProvider,
  type ISubAgentManager,
  type TaskToolArgs,
  type TaskOutputToolArgs,
  type ContextExtractionOptions,
  type IContextBridge,
  type SubAgentSystemOptions,
  type SubAgentSystem,
  // Manager
  SubAgentManager,
  SPECIALIZED_PRESETS,
  // Context Bridge
  ContextBridge,
  createContextBridge,
  estimateTokens,
  createContextSummaryForSubAgent,
  // Tools
  createTaskTool,
  createTaskOutputTool,
  registerSubAgentTools,
  // Factory
  createSubAgentSystem,
} from './subagent';

// Export session management
export {
  AgentSession,
  ConversationPersistenceCoordinator,
  ConversationPersistenceRuntime,
  ConversationIndexStore,
  ConversationManager,
  FileConversationStorage,
  FileAgentWorkspaceRuntimeStateRuntime,
  JournalProjection,
  JournalStorage,
  createAgentSession,
  createAgentWorkspaceRuntimeStateRuntime,
  createEmptyAgentWorkspaceRuntimeState,
  createSkillCreationKind,
  encodeCreationKindSegment,
  buildConversationHistoryClearedMessage,
  createPlanModeCreationMetadata,
  createSkillExecutionCreationMetadata,
  mergeCreationExecutionMetadata,
  buildConversationRecordSavePlan,
  createConversationId,
  createFileConversationStorage,
  createFileAgentWorkspaceRuntimeStateRuntime,
  createConversationPersistenceRuntime,
  createFileConversationPersistenceRuntime,
  getAgentWorkspaceRuntimeStateFilePath,
  createJournalStorage,
  createNodeJournalStorage,
  createJournalEntryId,
  createAgentTaskResultObservationLedger,
  createSessionTaskResultObservationRecorder,
  createTaskResultObservationJournalEntries,
  formatToolResultContext,
  getConversationWorkDirHash,
  hydrateAgentHistoryWithToolResults,
  isCanonicalConversationId,
  parseConversationId,
  projectConversationMessagesToAgentHistory,
  projectEntriesToHistory,
  runCancelMessageRuntime,
  runClearAllConversationsRuntime,
  runClearHistoryRuntime,
  runConfirmToolRuntime,
  runDeleteConversationRuntime,
  runNewConversationRuntime,
  runSwitchConversationRuntime,
  type ConfirmToolRuntimeInput,
  type ConversationControlAction,
  type ConversationControlConversationInput,
  type ConversationControlDisposable,
  type ConversationControlRuntimeEffects,
  type ConversationControlRuntimeMessage,
  type ConversationControlRuntimeResult,
  type ConversationControlRuntimeWarning,
  type ConversationControlRuntimeWarningCode,
  type DeleteConversationRuntimeInput,
  type DeleteConversationRuntimeOptions,
  type AgentHistoryEntry,
  type AgentWorkspaceRuntimeConversationState,
  type AgentWorkspaceRuntimeExecutionMode,
  type AgentWorkspaceRuntimeMediaCategory,
  type AgentWorkspaceRuntimeModelSelection,
  type AgentWorkspaceRuntimeSessionMode,
  type AgentWorkspaceRuntimeState,
  type AgentWorkspaceRuntimeStateFsOps,
  type AgentWorkspaceRuntimeStatePatch,
  type AgentWorkspaceRuntimeStateRuntime,
  type AgentWorkspaceRuntimeStateRuntimeOptions,
  type AgentWorkspaceRuntimeStateSource,
  type AgentWorkspaceRuntimeStatus,
  type AgentWorkspaceRuntimeTokenUsage,
  type CleanupPolicy,
  type Conversation,
  type ConversationIdOptions,
  type ConversationIndexMeta,
  type ConversationIndexStoreFsOps,
  type ConversationIndexStoreOptions,
  type ConversationManagerOptions,
  type DeleteConversationOptions,
  type ConversationMediaModelSelection,
  type ConversationRecord,
  type ConversationPersistenceCoordinatorMetrics,
  type ConversationPersistenceCoordinatorOptions,
  type ConversationPersistenceDiagnostic,
  type ConversationPersistenceDiagnosticCode,
  type ConversationPersistenceDisposeResult,
  type ConversationPersistenceFlushResult,
  type ConversationPersistenceOperationKind,
  type ConversationPersistenceOperationResult,
  type ConversationPersistenceStoragePort,
  type ConversationPersistenceSubmitResult,
  type ConversationPersistenceRuntimeOptions,
  type ConversationPersistenceRuntimeQueueResult,
  type ConversationPersistenceRuntimeResult,
  type ConversationPersistenceRuntimeStorage,
  type ConversationPersistenceRuntimeWarning,
  type ConversationSource,
  type ConversationStorage,
  type ConversationsIndexFile,
  type FileConversationStorageOptions,
  type IConversationIndexStore,
  type JournalEntry,
  type JournalFsOps,
  type JournalWriterOptions,
  type StateSnapshot,
  type SubAgentRef,
  type ParsedConversationId,
  type ResumedSessionState,
  type JournalReaderFsOps,
  type JournalReaderOptions,
  type JournalStorageFsOps,
  type IJournalProjection,
  type JournalProjectionOptions,
  type ConversationSummary,
  type AgentTaskResultObservationLedger,
  type RecordAgentTaskResultObservationInput,
  type RecordAgentTaskResultObservationResult,
  type RecordSessionTaskResultObservationInput,
  type SessionTaskResultObservationRecorderConfig,
  type TaskResultObservationJournalEntry,
  type IAgentSession,
  type AgentSessionConfig,
  type AgentEvent,
  type AgentEventType,
  type AgentHistoryToolCallContext,
  type AgentHistoryToolResultContext,
  type AgentHistoryWithToolContextMessage,
  type ConversationRecordProjectionConversation,
  type ConversationRecordSavePlan,
  type ConversationRecordSavePlanInput,
  type ProjectedAgentHistoryEntry,
  type ExecutionMode,
  type ExecutionContext,
  type CompressionResult,
  // Re-exported from permission
  type ToolConfirmationRequest as SessionToolConfirmationRequest,
  // Re-exported from validation
  type ValidationError as SessionValidationError,
  type ValidationWarning as SessionValidationWarning,
} from './session';

export {
  CHARACTER_DIALOGUE_DEFAULT_CONFIG,
  CharacterDialogueSession,
  buildCharacterDialogueTurnSystemPrompt,
  projectCharacterDialogueTranscriptToChatMessages,
  type CharacterDialogueResponder,
  type CharacterDialogueResponderInput,
  type CharacterDialogueResponderResult,
  type CharacterDialogueSendUserMessageOptions,
  type CharacterDialogueSessionConfig,
  type CharacterDialogueSessionOptions,
  type CharacterDialogueSessionSnapshot,
  type CharacterDialogueTurn,
} from './runtime/character-dialogue-session';

export {
  DEFAULT_CHARACTER_EVIDENCE_BUDGET,
  aggregateCharacterEvidenceFreshness,
  dedupeCharacterEvidenceChunks,
  normalizeCharacterEvidenceBudget,
  normalizeCharacterEvidenceTokens,
  projectCharacterEvidenceBundleToProfileFacts,
  rankCharacterEvidenceChunks,
  renderCharacterEvidenceBundle,
  scoreCharacterEvidenceChunk,
  trimCharacterEvidenceChunks,
  type CharacterEvidenceAuthority,
  type CharacterEvidenceBudget,
  type CharacterEvidenceBundle,
  type CharacterEvidenceChunk,
  type CharacterEvidenceLoader,
  type CharacterEvidenceMetadata,
  type CharacterEvidenceMetadataValue,
  type CharacterEvidenceMode,
  type CharacterEvidenceOmission,
  type CharacterEvidenceOmissionReason,
  type CharacterEvidenceRelevance,
  type CharacterEvidenceRelevanceSignal,
  type CharacterEvidenceRequest,
  type CharacterEvidenceScoreInput,
  type CharacterEvidenceSourceKind,
  type CharacterEvidenceSourceRef,
  type CharacterEvidenceTrimResult,
} from './runtime/character-evidence';

export {
  CreativeAiRunRuntime,
  createCreativeAiRunRuntime,
  type AcceptCreativeAiInvocationInput,
  type CreativeAiBackgroundWorkItemContext,
  type CreativeAiRunAcceptResult,
  type CreativeAiRunEvent,
  type CreativeAiRunEventType,
  type CreativeAiRunIdInput,
  type CreativeAiRunRuntimeOptions,
  type CreativeAiWorkItemIdInput,
  type ProjectCreativeAiSubAgentEventInput,
  type StartCreativeAiWorkItemInput,
} from './runtime/creative-ai-run-runtime';

// Export task management
export {
  TaskManager,
  createTaskManagerCreationTaskProjection,
  MemoryTaskStorage,
  FileTaskStorage,
  FileTaskStorageLoadError,
  StateTaskStorage,
  WorkspaceVisibleAgentTaskStorage,
  createFileTaskStorage,
  createFileWorkspaceVisibleAgentTaskStorage,
  createStateTaskStorage,
  getWorkspaceVisibleAgentTaskRecordsFilePath,
  MemoryTaskRecoveryStorage,
  FileTaskRecoveryStorage,
  StateTaskRecoveryStorage,
  createFileRecoveryStorage,
  createStateTaskRecoveryStorage,
  CLEANUP_TASK_STATUSES,
  DEFAULT_TASK_CLEANUP_INTERVAL_MS,
  DEFAULT_TASK_RETENTION_PERIOD_MS,
  DEFAULT_TASK_STORAGE_KEY,
  RECOVERABLE_TASK_STATUSES,
  buildTaskStorageCleanupPlan,
  buildAgentTaskHostPrivateLeaseDiagnostic,
  createAgentTaskHostPrivateLease,
  createWorkspaceVisibleAgentTaskRecord,
  AgentTaskResultObservationError,
  AgentTaskResultObservationCoordinator,
  AgentTaskResultObservationRuntime,
  DEFAULT_AGENT_TASK_RESULT_DELIVERY_POLICY,
  createAgentTaskResultEvidenceId,
  createAgentTaskResultFollowUpRequestId,
  createAgentTaskResultObservationId,
  createAgentTaskResultObservationRecords,
  createAgentTaskResultObservationCoordinator,
  createAgentTaskResultObservationRuntime,
  evaluateAgentTaskResultDelivery,
  filterRecoverableTasks,
  getAgentTaskResultDeliveryPolicy,
  isRecoverableTask,
  isRecoverableTaskStatus,
  isAgentTaskResultTerminalStatus,
  isTaskCleanupCandidate,
  isTaskCleanupStatus,
  normalizeAgentTaskResultDeliveryPolicy,
  normalizeAgentTaskResultObservation,
  normalizeAgentTaskResultRefs,
  type TaskManagerOptions,
  type TaskRunLease,
  type TaskTerminalEvent,
  type TaskTerminalCallback,
  type TaskTerminalSubscriptionOptions,
  type ConcurrencyConfig,
  type ICreationProjectedTaskStore,
  type IRuntimeTaskManager,
  type FileTaskStorageOptions,
  type StateTaskStorageAdapter,
  type StateTaskStorageOptions,
  type WorkspaceVisibleAgentTaskStorageOptions,
  type FileTaskRecoveryStorageOptions,
  type StateTaskRecoveryStorageAdapter,
  type StateTaskRecoveryStorageOptions,
  type TaskStorageCleanupPlan,
  type AgentTaskResultDeliveryDecision,
  type AgentTaskResultFollowUpScheduler,
  type AgentTaskResultObservationContinuationPort,
  type AgentTaskResultObservationCoordinatorDiagnostic,
  type AgentTaskResultObservationCoordinatorDiagnosticCode,
  type AgentTaskResultObservationCoordinatorOptions,
  type AgentTaskResultObservationDiagnosticCode,
  type AgentTaskResultObservationJournalPort,
  type AgentTaskResultObservationRecordPort,
  type AgentTaskResultObservationRecords,
  type AgentTaskResultObservationRuntimeAgentPort,
  type AgentTaskResultObservationRuntimeAgentRegistry,
  type AgentTaskResultObservationRuntimeOptions,
  type AgentTaskResultObservationRuntimeTaskPort,
  type AgentTaskResultObservationRuntimeTaskManagerTerminalInput,
  type AgentTaskResultObservationTerminalOptions,
  type HandleAgentTaskResultTerminalInput,
  type HandleAgentTaskResultTerminalResult,
  type NormalizeAgentTaskResultObservationInput,
  type ICreationTaskProjection,
  type ICreationTaskProjectionStore,
  type CreationTaskProjectionConfig,
  type CreationProjectedTaskArtifactBinding,
  type CreationProjectedTaskBinding,
  type CreationProjectedTaskPayload,
  type CreationProjectedTaskUpsertInput,
  getCreationProjectedTaskRunId,
  isCreationProjectedTaskPayload,
  toSerializableCreationProjectedTask,
  toCreationProjectedTaskPayload,
  buildCancelTaskActionPlan,
  buildClearCompletedTaskPlan,
  buildBackgroundTaskFailureUpdateView,
  buildRemoveTaskActionPlan,
  buildRetryTaskActionPlan,
  buildTaskResultOpenPlan,
  buildViewTaskResultActionPlan,
  createBackgroundTaskViewFromToolResultData,
  filterTasksForConversation,
  getTaskConversationId,
  getTaskResultUrl,
  matchesTaskConversation,
  mergeBackgroundTaskProgressView,
  runCancelTaskRuntime,
  runClearCompletedTasksRuntime,
  runRemoveTaskRuntime,
  runRetryTaskRuntime,
  runSendTasksRuntime,
  runViewTaskResultRuntime,
  toBackgroundTaskView,
  toBackgroundTaskViewStatus,
  toBackgroundTaskViewType,
  type CancelTaskActionPlan,
  type ClearCompletedTaskPlan,
  type RemoveTaskPlan,
  type RetryTaskPlan,
  type ConversationTasksRuntimeInput,
  type TaskActionRejectPlan,
  type TaskActionNoopPlan,
  type TaskActionRejectReason,
  type TaskMediaCandidate,
  type TaskRuntimeAction,
  type TaskRuntimeDeps,
  type TaskRuntimeEffects,
  type TaskRuntimeInput,
  type TaskRuntimeHostPrivateLeaseGuard,
  type TaskRuntimeMediaGateway,
  type TaskRuntimeMessage,
  type TaskRuntimeResult,
  type TaskRuntimeTaskManager,
  type TaskResultOpenPlan,
  type ViewTaskResultPlan,
  // Re-exported types from shared
  type Task,
  type TaskType,
  type TaskStatus,
  type TaskInput,
  type TaskOutput,
  type TaskProgressCallback,
  type ITaskManager,
  type ITaskStorage,
  type ITaskRecoveryStorage,
  type TaskRecoveryInfo,
  type SerializableTask,
  type TaskExecutor,
  type TaskExecutionContext,
  type TaskLifecycleMetadata,
  type AgentTaskResultDeliveryPolicy,
  type AgentTaskResultFollowUpRequest,
  type AgentTaskResultObservation,
  type AgentTaskResultRef,
  type AgentTaskResultRefKind,
  type AgentTaskResultSource,
  type AgentTaskResultTerminalStatus,
  type TaskCostPhase,
  type TaskInterruptPolicy,
  type TaskRecoverPolicy,
  type TaskRunMode,
  type BackgroundTaskView,
  type BackgroundTaskProgressPatch,
  type BackgroundTaskFailureUpdateOptions,
  type BackgroundTaskToolResultProjectionOptions,
  type BackgroundTaskViewStatus,
  type BackgroundTaskViewType,
  type AgentTaskHostPrivateLease,
  type AgentTaskHostSurface,
  type AgentTaskLeaseControl,
  type AgentTaskLeaseDiagnostic,
  type AgentTaskStorageScope,
  type WorkspaceVisibleAgentTaskRecord,
  MEDIA_PRODUCTION_WORKFLOW_PAYLOAD_KIND,
  MEDIA_PRODUCTION_WORKFLOW_STATE_OUTPUT_KEY,
  TaskBackedMediaProductionWorkflowStateStore,
  createMediaProductionWorkflowTaskInput,
  readMediaProductionWorkflowTaskState,
  type MediaProductionWorkflowTaskStatePort,
} from './task';

export {
  MEDIA_PRODUCTION_EARLY_STAGE_IDS,
  MediaProductionEarlyStageOrchestrator,
  type MediaProductionEarlyStageOrchestratorOptions,
  type MediaProductionEarlyStagePorts,
  type MediaProductionStageExecutionContext,
  type MediaProductionStageExecutionResult,
  type MediaProductionStageExecutorPort,
  type MediaProductionWorkflowStateStorePort,
  MediaProductionProjectAuthoringOrchestrator,
  type MediaProductionProjectAuthoringOrchestratorOptions,
  type MediaProductionProjectAuthoringPort,
  type MediaProductionProjectAuthoringPorts,
  type MediaProductionProjectAuthoringRequest,
} from './media-production';

// Export commands (builtin slash commands)
export {
  // Types
  type BuiltinCommandName,
  type BuiltinCommand,
  type CommandCategory,
  type CommandContext,
  type CommandResult,
  type CommandAction,
  type CommandHandler,
  type CommandHandlerRegistration,
  type SlashCommandSurface,
  type SlashCommandSkillLike,
  type SlashCommandCatalogEntry,
  type BuildExtensionCommandHostEffectPlanInput,
  type BuildExtensionCommandResultPayloadInput,
  type BuildExtensionSkillCommandResultPayloadInput,
  type ExtensionCommandHostEffect,
  type ExtensionCommandHostEffectPlan,
  type ExtensionCommandConversationSummary,
  type ExtensionCommandConversationSummarySource,
  type ExtensionCommandResultPayload,
  type ExtensionSkillCommandResultStatus,
  type ExtensionSlashCommandContextManager,
  type ExtensionSlashCommandConversationSource,
  type ExtensionSlashCommandExecutionDispatch,
  type ExtensionSlashCommandPlanModeSource,
  type ExtensionSlashCommandRuntimeDeps,
  type ExtensionSlashCommandRuntimeEffects,
  type ExtensionSlashCommandRuntimeInput,
  type ExtensionSlashCommandRuntimeResult,
  type ExtensionSlashCommandSettingsSource,
  type ExtensionSlashCommandSkillSource,
  // Constants
  COMMAND_ALIASES,
  BUILTIN_COMMANDS,
  // Functions
  buildExtensionCommandConversationSummaries,
  buildExtensionCommandHostEffectPlan,
  buildExtensionCommandResultPayload,
  buildExtensionSkillCommandResultPayload,
  buildExtensionSlashStatusPayload,
  runExtensionSlashCommandRuntime,
  resolveCommandName,
  normalizeSlashCommandName,
  parseBuiltinCommandArgs,
  shouldExecutePlanPromptAfterToggle,
  listSlashCommandCatalog,
  resolveSlashCommandCatalogEntry,
  getCliCommands,
  getExtensionCommands,
  getBuiltinCommand,
  isBuiltinCommand,
  getAllCommandNames,
  // Handlers
  handleHelp,
  handleStatus,
  handleClear,
  handleExit,
  handleConfig,
  handleModel,
  handleSettings,
  handlePermissions,
  handleInit,
  handleNew,
  handleResume,
  handleCompact,
  handlePlan,
  handleSkills,
  handleCommands,
  handleTools,
  handleTasks,
  handleMcp,
  buildAgentTerminalHelpSemantic,
  executeAgentTerminalSkillsSemantic,
  executeAgentTerminalCommandsSemantic,
  executeAgentTerminalToolsSemantic,
  type AgentTerminalSkillRow,
  type AgentTerminalToolRow,
  type AgentTerminalHelpSemanticResult,
  type AgentTerminalSkillsSemanticResult,
  type AgentTerminalCommandsSemanticResult,
  type AgentTerminalToolsSemanticResult,
  type AgentTerminalResourceCommandSemanticResult,
  type AgentCommandSessionSemanticResult,
  type AgentCommandConfigSnapshot,
  type AgentCommandConfigSemanticResult,
  type AgentCommandCoreSemanticResult,
  type AgentCommandShellSemanticResult,
  type AgentCommandSemanticResult,
  isAgentCommandSemanticFailure,
  // Utilities
  generateExtensionStatusData,
  // Executor
  parseSlashCommand,
  isSlashCommand,
  executeBuiltinCommand,
  executeSlashCommand,
  getCommandHandler,
} from './commands';

// Export input processing
export {
  InputProcessor,
  createInputProcessor,
  NodeFileReader,
  createNodeFileReader,
  DEFAULT_MENTION_EXCLUDED_DIRECTORIES,
  DEFAULT_MENTION_EXCLUDE_GLOB,
  isMentionExcludedPath,
  createWorkspaceFileIgnoreRules,
  matchesGitignoreRules,
  normalizeRelativePath,
  parseGitignoreRules,
  shouldIgnoreWorkspaceFile,
  VSCodeFileReader,
  createVSCodeFileReader,
  type VSCodeWorkspaceAPI,
  type WorkspaceFileIgnoreDecision,
  type WorkspaceFileIgnoreReason,
  type WorkspaceFileIgnoreRules,
  type FileReference,
  type ProcessedInput,
  type InputProcessorOptions,
  type IFileReader,
  type IInputProcessor,
} from './input';

// Export workspace/content layout helpers
export {
  NEKO_AGENTS_FILE_NAME,
  NEKO_CONTENT_DIR,
  NEKO_CONTENT_SUBDIRS,
  resolveAgentsFile,
  resolveNekoContentDir,
  resolvePersonalAgentsFile,
  resolvePersonalNekoContentDir,
  resolveProjectAgentsFile,
  resolveProjectNekoContentDir,
  type NekoContentSource,
  type NekoContentSubdir,
} from './workspace';
