/**
 * @neko/agent - Agent Application Package
 *
 * This package provides the agent runtime for AI-powered task execution.
 * It can run standalone (without platform) or integrated with platform.
 *
 * Standalone mode:
 * - Uses built-in LLM client
 * - Full MCP support
 * - Skill system
 *
 * Integrated mode:
 * - Uses platform's LLM routing
 * - Media generation via platform
 * - Workflow execution via platform
 */

// Re-export shared types for convenience
export type {
  // Agent types
  AgentState,
  AgentConfig,
  AgentContext,
  AgentStep,
  AgentResult,
  AgentCheckpoint,
  IAgentExecutor,
  IAgentRuntime,
  // Hook types
  ExecutorHooks,
  ToolCallInfo,
  ToolResultWithMeta,
  ThinkContext,
  // Skill types (from shared - Claude-compatible)
  Skill,
  SlashCommand,
  SkillMatch,
  SkillSource,
  SkillInjection,
  ISkillService,
  ISkillRegistry,
  ISkillMatcher,
  ISkillInjector,
  SkillFrontmatter,
  CommandFrontmatter,
  ParsedSkillFile,
  SkillLoadResult,
  SkillLoadError,
  ISkillFileSystem,
  SkillSummary,
  SkillValidationResult,
  // MCP types
  IMCPManager,
  IMCPClient,
  MCPServerConfig,
  MCPToolDefinition,
  MCPToolResult,
  MCPResource,
  MCPPrompt,
  // Tool types
  IToolRegistry,
  Tool,
  ToolResult,
  ToolCategory,
  ToolCallRequest,
  // Platform types (for integration)
  IPlatform,
  IService,
  ChatMessage,
  ServiceResponse,
  StreamChunk,
  ServiceOptions,
  ToolDefinition,
  LLMProviderConfig,
} from '@neko/shared';

export {
  ExperimentRunner,
  applyAblationToggles,
  extractAblationMarker,
  MetricsHooks,
  buildComparison,
  formatComparisonMarkdown,
  BASELINE,
  NO_COMPRESSION,
  NO_CREATIVE_COMPRESSION,
  NO_SKILL_DISCOVERY,
  NO_SKILL_INJECTION,
  NO_DYNAMIC_TOOLSETS,
  NO_VALIDATION,
  NO_RETRY,
  NO_SETTINGS_HOOKS,
  NO_PROJECT_MEMORY,
  NO_COMPACT_LOGGING,
  NO_AUTO_MEMORY_EXTRACTION,
  NO_MEMORY_RECALL,
  NO_TRAITS,
  NO_THINKING,
  ALWAYS_ONLY_TOOLS,
  PLAN_PERMISSION_MODE,
  ASK_PERMISSION_MODE,
  SINGLE_ITERATION,
  NO_ALL_COMPRESSION,
  NO_ALL_SKILLS,
  NO_ALL_EXTERNAL,
  MINIMAL,
  createStandardAblationSuite,
  createGroupAblationSuite,
  createParameterAblationSuite,
} from './experiment';
export type {
  AblationToggles,
  AblationMarkerHook,
  EvaluationResult,
  ExperimentEvaluator,
  ExperimentIsolationMode,
  ExperimentConfig,
  ExperimentOutputFile,
  ExperimentOutputWriter,
  ExperimentRunDescriptor,
  ExperimentRunIsolation,
  ExperimentVariant,
  IExperimentSession,
  ISessionFactory,
  TokenMetrics,
  ToolCallMetric,
  TurnMetrics,
  ExperimentMetrics,
  VariantRunResult,
  VariantResult,
  ExperimentResult,
  ComparisonEntry,
  ExperimentProgressEvent,
} from './experiment';

export {
  composeBeforeThinkHooks,
  createFeedbackCoordinator,
  type FeedbackCoordinatorConfig,
  type FeedbackCycle,
  type FeedbackDecision,
  type FeedbackEvaluationContext,
  type FeedbackSignal,
  type IFeedbackEvaluator,
  type FeedbackMemoryExtractionInput,
  type FeedbackMemoryExtractionOutcome,
  type FeedbackMemoryExtractionResult,
  type FeedbackMemoryExtractionSkipped,
  createQualityReviewEvidence,
  type IFeedbackCoordinator,
  type QualityReviewEvidenceInput,
  type QualityReviewEvidenceResult,
  type QualityReviewEvidenceSummary,
  type QualityReviewEvaluationSummary,
  type QualityReviewFeedbackPayload,
} from './feedback';

export {
  parseProviderCardMarkdown,
  ProviderCardRegistry,
  createProviderCardRegistry,
  ProviderRouter,
  createProviderRouter,
  loadProviderCardDirectory,
  registerProviderCardDirectory,
  registerRuntimeProviderCardDirectories,
  type ParseProviderCardOptions,
  type LoadProviderCardDirectoryOptions,
  type RegisterProviderCardDirectoryOptions,
  type ProviderCardLoaderFs,
  type ProviderCardDirent,
  type ProviderCardLoadError,
  type ProviderCardRuntimeLogger,
  type RegisterRuntimeProviderCardDirectoriesOptions,
  type RuntimeProviderCardDirectoryRegistrationResult,
  createProviderExpressionPromptFragments,
  type ProviderExpressionContextOptions,
} from './provider';

export {
  PERCEPTION_AUDIO_TRANSCRIBE_METADATA,
  PERCEPTION_IMAGE_SIMILARITY_METADATA,
  PERCEPTION_IMAGE_CLASSIFY_METADATA,
  PERCEPTION_DESCRIBE_INPUT_METADATA,
  PERCEPTION_VIDEO_DETECT_SHOTS_METADATA,
  PerceptionAudioTranscribeTool,
  PerceptionImageSimilarityTool,
  PerceptionImageClassifyTool,
  PerceptionDescribeInputTool,
  PerceptionVideoDetectShotsTool,
  createPerceptionTools,
  perceptionToolGroup,
  type PerceptionAudioTranscribeToolConfig,
  type PerceptionImageSimilarityToolConfig,
  type PerceptionImageClassifyToolConfig,
  type PerceptionToolMetadata,
  type PerceptionToolResult,
  type PerceptionClassifyClient,
  type PerceptionDetectShotsClient,
  type PerceptionSimilarityClient,
  type PerceptionTranscribeClient,
  BuiltinTool,
  createTool,
  ToolRegistry,
  createToolRegistry,
  ToolCategoryRegistry,
  createToolCategoryRegistry,
  ToolInjectionManager,
  createToolInjectionManager,
  // Core meta tools
  ActivateSkillTool,
  DeactivateSkillTool,
  GetContextTool,
  createCoreMetaTools,
  type ISkillProvider,
  type SkillProviderFactory,
  type SkillProviderMaybePromise,
  // Core file/system tools
  ReadTool,
  WriteTool,
  BashTool,
  type BashToolOptions,
  ListDirectoryTool,
  GrepTool,
  type GrepToolOptions,
  MemoryWriteTool,
  createCoreTools,
  type CoreToolsOptions,
  // Creative tool runtimes
  createPuppetFaceTools,
  type PuppetFaceToolsDeps,
  type PuppetFaceToolsLogger,
  PuppetFaceRuntime,
  buildPuppetFaceParameterSchemaPrompt,
  createPuppetFaceRuntime,
  detectPuppetFaceImageMimeType,
  diffPuppetFaceParams,
  parsePuppetFaceJsonResponse,
  validateAndClampPuppetFaceParams,
  type PuppetFaceAdjustInput,
  type PuppetFaceAdjustResult,
  type PuppetFaceAdjustSuccess,
  type PuppetFaceErrorResult,
  type PuppetFaceGenerateInput,
  type PuppetFaceGenerateResult,
  type PuppetFaceGenerateSuccess,
  type PuppetFaceImageInput,
  type PuppetFaceImageResult,
  type PuppetFaceImageSuccess,
  type PuppetFaceParamChanges,
  type PuppetFaceParams,
  type PuppetFaceRuntimeDeps,
  // Script scene search runtime
  ScriptEmbeddingIndex,
  buildScriptSceneTextInputs,
  keywordSearchScriptScenes,
  normalizeScriptSceneTopK,
  searchScriptScenes,
  tokenizeScriptSceneQuery,
  type EmbedFn,
  type SceneEmbedding,
  type SceneTextInput,
  type ScriptSceneSearchInput,
  type ScriptSceneSearchResult,
  type ScriptSceneSpan,
  type SearchResult,
  // Injection constants
  DEFAULT_INJECTION_CONFIG,
  CORE_TOOLS,
} from './tools';

export {
  ControlPlane,
  FeedbackStageController,
  ArtifactRegistry,
  StageRegistry,
  createArtifactRegistry,
  createControlPlane,
  createDefaultArtifactRegistry,
  createDefaultControlPlane,
  createDefaultStageRegistry,
  createStageRegistry,
  type ArtifactDescriptor,
  type ControlPlaneConfig,
  type ControlPlaneDecision,
  type ControlPlaneDecisionInput,
  type IArtifactRegistry,
  type IControlPlane,
  type IReadonlyArtifactRegistry,
  type IStageController,
  type IStageRegistry,
  type StageControllerContext,
  type StageDescriptor,
  type StageRiskLevel,
  type StageTransitionGuidance,
} from './control-plane';

// Export plan parsing and message projection helpers
export {
  buildPlanApprovalDispatchPlan,
  buildPlanApprovalExecutionDispatch,
  buildPlanApprovalExecutionOverrides,
  buildPlanApprovalExecutionMessage,
  buildPlanFileReadErrorMessage,
  buildPlanRejectionFeedbackMessage,
  buildPlanRejectionFeedbackStreamMessage,
  buildPlanStatusUpdateMessage,
  buildPromptModeChangedMessage,
  createPlanContentBlockFromToolResultData,
  parsePlanMarkdown,
  projectPlanStepActionReview,
  projectPlanStepModificationReview,
  runPlanApprovalRuntime,
  runPlanRejectionRuntime,
  runPlanStepActionRuntime,
  runPlanStepModificationRuntime,
  type Plan,
  type PlanApprovalDispatchPlan,
  type PlanApprovalDispatchPlanInput,
  type PlanApprovalExecutionDispatch,
  type PlanFileReadErrorMessage,
  type PlanApprovalRuntimeInput,
  type PlanApprovalRuntimeResult,
  type PlanStep,
  type PlanPromptMode,
  type PlanRejectionRuntimeInput,
  type PlanRejectionFeedbackStreamMessage,
  type PlanReviewDecision,
  type PlanReviewConversationStore,
  type PlanReviewRuntimeEffects,
  type PlanReviewRuntimeMessage,
  type PlanReviewRuntimeResult,
  type PlanStatusUpdateMessage,
  type PlanStepActionRuntimeInput,
  type PlanStepModificationRuntimeInput,
  type PlanStepReviewAction,
  type PlanStepReviewProjection,
  type PlanStepStatusUpdateMessage,
  type PlanToolResultProjection,
  type PlanToolResultProjectionOptions,
  type PromptModeChangedMessage,
} from './plan';

// Export logger
export { setRootLogger, getLogger as getAgentLogger } from './utils/logger';

// Export errors
export { AgentError, type AgentErrorCategory, type AgentErrorInfo } from './errors';

// Export executor
export { AgentExecutor, createAgentExecutor, type AgentExecutorOptions } from './executor';

// Export hooks
export {
  RetryHooks,
  MemoryHooks,
  composeHooks,
  createRetryHooks,
  createMemoryHooks,
  type RetryHooksOptions,
  type MemoryHooksOptions,
} from './hooks';

// Export memory
export {
  FileProjectMemoryManager,
  createFileProjectMemoryManager,
  KeyFactExtractor,
  MemoryRecall,
} from './memory';
export type { KeyFactExtractorOptions, MemoryRecallOptions, RecalledMemory } from './memory';

// Export MCP
export {
  StdioMCPClient,
  HttpMCPClient,
  createMCPClient,
  MCPManager,
  MCPTool,
  MCP_SERVER_TEST_TIMEOUT_MS,
  buildMCPServerStoreEntry,
  buildMCPServerTestPlan,
  buildMCPServerTestResultMessage,
  connectMCPServersRuntime,
  createMCPTools,
  createAllMCPTools,
  MCPTestService,
  getMCPTestService,
  runMCPServerTestRuntime,
  type MCPToolCallManager,
  type MCPToolDiscoveryManager,
  type MCPRuntimeBootstrapLogger,
  type MCPRuntimeBootstrapOptions,
  type MCPRuntimeBootstrapResult,
  type MCPRuntimeConnectionFailure,
  type MCPRuntimeManager,
  type MCPRuntimeConnectionStateSink,
  type MCPRuntimeConnectionStatus,
  type MCPRuntimeToolRegistry,
  parseMCPServerArgsInput,
  type MCPTestConfig,
  type MCPTestResult,
  type MCPServerTestRuntimeEffects,
  type MCPServerTestRuntimeResult,
  type MCPServerStoreEntry,
  type MCPServerTestInput,
  type MCPServerTestPlan,
  type MCPServerTestResultMessage,
} from './mcp';

// Export validation
export {
  // Types
  type ImageConstraints,
  type OutputConstraints,
  type ValidationHooksOptions,
  type ValidationError,
  type ValidationWarning,
  type ValidationResult,
  type ValidationErrorType,
  type ImageInfo,
  type MermaidValidationResult,
  type MermaidBlockInfo,
  type MermaidBlockValidationResult,
  type JsonBlockInfo,
  type JsonBlockValidationResult,
  type ValidationResultWithBlocks,
  type ConsistencyCheckToolsDeps,
  type QualityCheckToolsDeps,
  // Constants
  DEFAULT_IMAGE_CONSTRAINTS,
  DEFAULT_OUTPUT_CONSTRAINTS,
  // Image Validator
  ImageValidator,
  ImageValidationError,
  createImageValidator,
  // Output Validator
  OutputValidator,
  createOutputValidator,
  // Validation Hooks
  ValidationHooks,
  createValidationHooks,
  // Extractors
  MermaidExtractor,
  JsonExtractor,
  createMermaidExtractor,
  createJsonExtractor,
  // Validators
  MermaidValidator,
  JsonSchemaValidator,
  LengthValidator,
  createMermaidValidator,
  createJsonSchemaValidator,
  createLengthValidator,
  // Checkers
  MermaidBlockChecker,
  createMermaidBlockChecker,
  // Quality / consistency tool factories
  createConsistencyCheckTools,
  createQualityCheckTools,
} from './validation';

// Export permission
export {
  // Types
  type PermissionMode,
  type PermissionDecision,
  type PermissionRules,
  type PermissionConfig,
  type PermissionCheckResult,
  type ToolConfirmationRequest,
  type ToolConfirmationResponse,
  type ConfirmToolCallback,
  type PlanFileResult,
  type PermissionHooksOptions,
  // Constants
  DEFAULT_READ_ONLY_TOOLS,
  READ_ONLY_MCP_PREFIXES,
  DEFAULT_PERMISSION_CONFIG,
  PLAN_MODE_SYSTEM_REMINDER,
  PLAN_FILE_PATH,
  // Rule Matcher
  PermissionRuleMatcher,
  createPermissionRuleMatcher,
  normalizeToolCall,
  matchesPattern,
  isInPatternList,
  isReadOnlyTool,
  isPlanFileWrite,
  // Permission Hooks
  PermissionHooks,
  createPermissionHooks,
  // Creative Permission
  CREATIVE_PLAN_TOOLS,
  ToolTraitsRegistry,
  DEFAULT_CREATIVE_TOOL_TRAITS,
} from './permission';

// Export prompt file projection
export {
  DEFAULT_AGENTS_FILE_CONTENT,
  DEFAULT_NEW_PROMPT_NAME,
  PROMPT_FILE_EXTENSION,
  buildAgentsFileLoadPlan,
  buildAgentsFilePlan,
  buildPromptConfigFilePlan,
  buildPromptFileContent,
  createPromptFileRuntime,
  ensurePromptFileExtension,
  extractPromptNameFromContent,
  generatePromptFileId,
  generatePromptFileName,
  projectPromptFileInfo,
  promptFileInfoToConfig,
  shouldScanPromptFile,
  syncPromptFilesWithConfig,
  type AgentsFileLoadCandidate,
  type PromptFileInfo,
  type PromptFileScanResult,
  type PromptFileScanResult as AgentPromptFileScanResult,
  type AgentsFileFailurePlan,
  type AgentsFilePlan,
  type LoadedAgentsFile,
  type PromptFileRuntime,
  type PromptFileRuntimeFs,
  type PromptFileRuntimeLogger,
  type PromptFileRuntimeOptions,
  type PromptFileRuntimePath,
  type PromptFileRuntimeStatLike,
  type PromptFileSaveResult,
  type PromptConfigFilePlan,
  type SavePromptFileInput,
  PromptManager,
  createPromptManager,
  // System Prompt Builder
  SystemPromptBuilder,
  createSystemPromptBuilder,
  createConversationPromptModeRuntime,
  runSendConversationPromptModeRuntime,
  runSetConversationPromptModeRuntime,
  runToggleConversationPromptModeRuntime,
  runSystemPromptAgentsFileLoadRuntime,
  getDefaultPersonalPath,
  hasAgentsFile,
  BUILTIN_PROMPTS,
  BUILTIN_DEFAULT_PROMPT_EN,
  BUILTIN_DEFAULT_PROMPT_ZH,
  BUILTIN_PLAN_PROMPT_EN,
  BUILTIN_PLAN_PROMPT_ZH,
  type ISystemPromptBuilder,
  type SystemPromptBuilderConfig,
  type SystemPromptAgentsFileRuntimeDeps,
  type SystemPromptAgentsFileRuntimeInput,
  type ConversationPromptModeRuntime,
  type ConversationPromptModeRuntimeOptions,
  type ConversationPromptModeSnapshot,
  type PromptMode,
  type PromptLocale,
  type AgentsSource,
  type AgentsLoadResult,
  type BuiltinPromptKey,
  // Re-exported types from shared
  type Prompt,
  type PromptVariable,
  type PromptCategory,
  type RenderedPrompt,
  type IPromptManager,
} from './prompt';

// Export skill
export {
  // Core classes
  SkillRegistry,
  SkillLoader,
  createNodeSkillLoader,
  SkillInjector,
  SkillMatcher,
  KeywordSkillMatcher,
  createCommandBackedSkill,
  createLazyCommandBackedSkill,
  ToolGuard,
  NoOpToolGuard,
  createToolGuard,
  // Skill Service
  SkillService,
  createSkillService,
  // Activation-time subpackage guard (ADR §5.2.10)
  assertSubpackagesAvailable,
  SkillActivationError,
  type ISubpackageResolver,
  type SubpackageInfo,
  type SkillActivationIssue,
  type SkillActivationIssueCode,
  // Builtins
  registerBuiltins,
  builtinSkills,
  builtinToolGroups,
  registerBuiltinToolGroups,
  // ToolGroup Registry
  ToolGroupRegistry,
  createToolGroupRegistry,
  projectRuntimeToolGroup,
  projectRuntimeToolGroups,
  // Skill Conflict Resolver
  SkillConflictResolver,
  createSkillConflictResolver,
  SkillRegistryPopulator,
  // Path Matcher
  matchSkillPaths,
  globMatch,
  type SkillPathInfo,
  // Markdown Parser
  MarkdownParser,
  createMarkdownParser,
  // Types
  type IToolGuard,
  type ToolCallInput,
  type ToolGuardResult,
  type SkillDiscoveryResult,
  type SkillApplicationResult,
  type LazySkillRegistryPopulateInput,
  type LazySkillRegistryScanGroup,
  type LazySkillRegistryScanResult,
  type ConfirmSkillCallback as ConfirmSkillCallbackFn,
  type SkillServiceConfig,
  type LazySkill,
  type LazyCommand,
  type LazySkillLoadResult,
  type IMarkdownParser,
  type YamlValue,
  appendSkillFileScanLoadResult,
  buildSkillDirectoryLoadFailureResult,
  buildCommandFileCreationPlan,
  buildCommandFileDeletionPlan,
  buildCommandFileOpenPlan,
  buildSkillFileScanPlan,
  buildSkillFileContent,
  buildSkillFileCreationPlan,
  buildSkillDirectoryDeletionPlan,
  buildSkillDirectoryDuplicationPlan,
  createEmptySkillFileScanResult,
  buildSkillSupportFileOpenPlan,
  normalizeSkillFrontmatter,
  normalizeDuplicatedSkillContent,
  buildCommandFileContent,
  shouldCopySkillDirectoryEntry,
  buildSkillAwareSystemPrompt,
  buildRuntimeSkillAwareSystemPrompt,
  buildSkillInjectionMessage,
  buildSkillsListMessage,
  SKILL_FILE_WATCH_DEBOUNCE_MS,
  SKILL_PATH_TRIGGER_DEBOUNCE_MS,
  createSkillFileRuntime,
  createRuntimeSkillLazySync,
  ConversationSkillRuntime,
  createConversationSkillProvider,
  createRuntimeSkillBootstrap,
  getEnabledSkillPromptEntries,
  populateLazyRuntimeSkillRegistry,
  toSkillPromptEntries,
  toConfiguredSkillFileCatalog,
  resolveSkillPathTriggers,
  type ActiveSkillState,
  type ApplySlashSkillCommandInput,
  type ConversationSkillAgentBridge,
  type ConversationSkillProviderEffects,
  type ConversationSkillProviderOptions,
  type ConversationSkillRuntimeDeps,
  type ConversationSkillRuntimeLogger,
  type ExecuteSkillInput,
  type SkillFileScanGroup,
  type SkillFileScanResult,
  type SkillFileScanResult as AgentSkillFileScanResult,
  type SkillFileScanGroupOf,
  type SkillFileScanResultOf,
  type LazySkillFileScanResult,
  type SkillInjectionMessage,
  type SkillsListMessage,
  type ConfiguredSkillFileCatalog,
  type BuildSkillFileContentOptions,
  type BuildSkillAwareSystemPromptInput,
  type BuildRuntimeSkillAwareSystemPromptInput,
  type CommandFileCreationPlan,
  type CommandFileDeletionPlan,
  type CommandFileOpenPlan,
  type CreateCommandFileInput,
  type CreateSkillFileInput,
  type DeleteCommandFileInput,
  type DeleteSkillDirectoryInput,
  type DuplicateSkillDirectoryInput,
  type ResolveSkillPathTriggersOptions,
  type SkillFileLoadResultOf,
  type SkillFileRuntime,
  type SkillFileRuntimeDirentLike,
  type SkillFileRuntimeFs,
  type SkillFileRuntimeLoader,
  type SkillFileRuntimeLogger,
  type SkillFileRuntimeOptions,
  type SkillFileRuntimePath,
  type SkillFileScanError,
  type SkillFileScanKind,
  type SkillFileScanPlan,
  type SkillFileScanPlanEntry,
  type SkillFileSource,
  type SkillDirectoryDeletionPlan,
  type SkillDirectoryDuplicationPlan,
  type SkillFileCreationPlan,
  type SkillFileOperationFailurePlan,
  type SkillPromptEntry,
  type PopulateLazyRuntimeSkillRegistryInput,
  type RuntimeSkillLazySync,
  type RuntimeSkillLazySyncLogger,
  type RuntimeSkillLazySyncOptions,
  type RuntimeSkillAwareSystemPromptResult,
  type RuntimeSkillBootstrap,
  type RuntimeSkillBootstrapLogger,
  type RuntimeSkillBootstrapOptions,
  type RuntimeSkillProviderState,
  type RuntimeToolGroupRegistryView,
  type SkillRegistryPopulateInput,
  type SkillRegistryPopulationSummary,
  type SkillRegistryScanGroup,
  type SkillRegistryScanResult,
  type SkillPathTriggerMatch,
  type SkillSupportFileOpenPlan,
  type SkillSupportFileOpenType,
} from './skill';

// Re-export skill utility functions from shared
export {
  toSkillSummary,
  validateSkill,
  createSkill,
  toCommandSummary,
  validateCommand,
  createCommand,
  parseAllowedTools,
  isToolAllowed,
  extractSupportFileRefs,
  SKILL_DIRECTORIES,
  COMMAND_DIRECTORIES,
} from '@neko/shared';

// Export context management
export {
  LayeredContextManager,
  createLayeredContextManager,
  ConversationCompressor,
  createConversationCompressor,
  ContextPersistenceManager,
  InMemoryContextStorage,
  createContextPersistenceManager,
  LLMSummarizer,
  createLLMSummarizer,
  DEFAULT_SUMMARIZER_CONFIG,
  type LLMSummarizerConfig,
} from './context';

// Export hook-loader
export {
  HookLoader,
  createHookFileRuntime,
  HookRuntimeManager,
  createHookLoader,
  createHookRuntimeManager,
  createProjectHookRuntimeManager,
  HOOK_DIRECTORIES,
  DEFAULT_HOOK_METADATA,
  HOOK_FILE_WATCH_DEBOUNCE_MS,
  HOOK_MARKDOWN_FILE_EXTENSION,
  buildHookDirectoryScanError,
  buildHookFileReadError,
  parseHookMarkdownFile,
  parseSimpleHookYaml,
  shouldScanHookFile,
  toConfiguredHookCatalog,
  type HookSource,
  type HookMetadata,
  type LoadedHook,
  type HookLoadResult,
  type HookLoadError,
  type IHookFileSystem,
  type IHookCompiler,
  type HookLoaderOptions,
  type CompileResult,
  type HookCompilerOptions,
  type HookRuntimeDisposable,
  type HookRuntimeLoader,
  type HookRuntimeLogger,
  type HookRuntimeManagerOptions,
  type HookRuntimeReloadEvent,
  type HookRuntimeReloadListener,
  type ProjectHookRuntimeManagerOptions,
  type HookFileRuntime,
  type HookFileRuntimeDirentLike,
  type HookFileRuntimeFs,
  type HookFileRuntimeLogger,
  type HookFileRuntimeOptions,
  type HookFileRuntimePath,
  type HookFileWatchEntry,
  type HookFileParseResult,
  type HookFileScanResult,
  type HookRequireFn,
  type HookSandboxModuleExecutorOptions,
  type HookTransform,
  type HookTransformOptions,
  type HookTransformResult,
  type HookModuleExports,
  DEFAULT_HOOK_ALLOWED_BUILTINS,
  DEFAULT_HOOK_PACKAGE_STUBS,
  DEFAULT_HOOK_SANDBOX_TIMEOUT_MS,
  buildHookTransformOptions,
  createHookCompiler,
  createHookSandboxModuleExecutor,
  createSafeHookRequire,
} from './hook-loader';

// Export subagent
export {
  // Types
  type SubAgentRunMode,
  type SubAgentStatus,
  type SpecializedAgentType,
  type ModelTier,
  type SubAgentConfig,
  type SpecializedAgentPreset,
  type SubAgentResult,
  type SubAgentEventType,
  type SubAgentEvent,
  type SubAgentEventListener,
  type SubAgentManagerDeps,
  type SubAgentExecutor,
  type SubAgentCreateAgentContext,
  type SubAgentSkillContentProvider,
  type ISubAgentManager,
  type TaskToolArgs,
  type TaskOutputToolArgs,
  type ContextExtractionOptions,
  type IContextBridge,
  type SubAgentSystemOptions,
  type SubAgentSystem,
  // Manager
  SubAgentManager,
  SPECIALIZED_PRESETS,
  // Context Bridge
  ContextBridge,
  createContextBridge,
  estimateTokens,
  createContextSummaryForSubAgent,
  // Tools
  createTaskTool,
  createTaskOutputTool,
  registerSubAgentTools,
  // Factory
  createSubAgentSystem,
} from './subagent';

// Export session management
export {
  AgentSession,
  ConversationPersistenceRuntime,
  ConversationIndexStore,
  ConversationManager,
  FileConversationStorage,
  JournalProjection,
  JournalStorage,
  createAgentSession,
  createSkillRunKind,
  encodeRunKindSegment,
  buildConversationHistoryClearedMessage,
  createPlanModeIdcMetadata,
  createSkillExecutionIdcMetadata,
  mergeIdcExecutionMetadata,
  buildConversationRecordSavePlan,
  createConversationId,
  createFileConversationStorage,
  createConversationPersistenceRuntime,
  createFileConversationPersistenceRuntime,
  createJournalStorage,
  createNodeJournalStorage,
  createJournalEntryId,
  formatToolResultContext,
  getConversationWorkDirHash,
  hydrateAgentHistoryWithToolResults,
  isCanonicalConversationId,
  parseConversationId,
  projectConversationMessagesToAgentHistory,
  projectEntriesToHistory,
  runCancelMessageRuntime,
  runClearAllConversationsRuntime,
  runClearHistoryRuntime,
  runConfirmToolRuntime,
  runDeleteConversationRuntime,
  runNewConversationRuntime,
  runStopAgentRuntime,
  runSwitchConversationRuntime,
  type ConfirmToolRuntimeInput,
  type ConversationControlAction,
  type ConversationControlConversationInput,
  type ConversationControlDisposable,
  type ConversationControlRuntimeEffects,
  type ConversationControlRuntimeMessage,
  type ConversationControlRuntimeResult,
  type ConversationControlRuntimeWarning,
  type ConversationControlRuntimeWarningCode,
  type AgentHistoryEntry,
  type CleanupPolicy,
  type Conversation,
  type ConversationIdOptions,
  type ConversationIndexMeta,
  type ConversationIndexStoreFsOps,
  type ConversationIndexStoreOptions,
  type ConversationManagerOptions,
  type ConversationMediaModelSelection,
  type ConversationRecord,
  type ConversationPersistenceRuntimeOptions,
  type ConversationPersistenceRuntimeQueueResult,
  type ConversationPersistenceRuntimeResult,
  type ConversationPersistenceRuntimeStorage,
  type ConversationPersistenceRuntimeWarning,
  type ConversationSource,
  type ConversationStorage,
  type ConversationsIndexFile,
  type FileConversationStorageOptions,
  type IConversationIndexStore,
  type JournalEntry,
  type JournalFsOps,
  type JournalWriterOptions,
  type StateSnapshot,
  type SubAgentRef,
  type ParsedConversationId,
  type ResumedSessionState,
  type JournalReaderFsOps,
  type JournalReaderOptions,
  type JournalStorageFsOps,
  type IJournalProjection,
  type JournalProjectionOptions,
  type ConversationSummary,
  type IAgentSession,
  type AgentSessionConfig,
  type AgentEvent,
  type AgentEventType,
  type AgentHistoryToolCallContext,
  type AgentHistoryToolResultContext,
  type AgentHistoryWithToolContextMessage,
  type ConversationRecordProjectionConversation,
  type ConversationRecordSavePlan,
  type ConversationRecordSavePlanInput,
  type ProjectedAgentHistoryEntry,
  type ExecutionMode,
  type ExecutionContext,
  type CompressionResult,
  // Re-exported from permission
  type ToolConfirmationRequest as SessionToolConfirmationRequest,
  // Re-exported from validation
  type ValidationError as SessionValidationError,
  type ValidationWarning as SessionValidationWarning,
} from './session';

// Export task management
export {
  TaskManager,
  createTaskManagerIdcTaskProjection,
  MemoryTaskStorage,
  FileTaskStorage,
  StateTaskStorage,
  createFileTaskStorage,
  createStateTaskStorage,
  MemoryTaskRecoveryStorage,
  FileTaskRecoveryStorage,
  createFileRecoveryStorage,
  CLEANUP_TASK_STATUSES,
  DEFAULT_TASK_CLEANUP_INTERVAL_MS,
  DEFAULT_TASK_RETENTION_PERIOD_MS,
  DEFAULT_TASK_STORAGE_KEY,
  RECOVERABLE_TASK_STATUSES,
  buildTaskStorageCleanupPlan,
  filterRecoverableTasks,
  isRecoverableTask,
  isRecoverableTaskStatus,
  isTaskCleanupCandidate,
  isTaskCleanupStatus,
  type TaskManagerOptions,
  type ConcurrencyConfig,
  type IIdcProjectedTaskStore,
  type IRuntimeTaskManager,
  type FileTaskStorageOptions,
  type StateTaskStorageAdapter,
  type StateTaskStorageOptions,
  type FileTaskRecoveryStorageOptions,
  type TaskStorageCleanupPlan,
  type IIdcTaskProjection,
  type IIdcTaskProjectionStore,
  type IdcTaskProjectionConfig,
  type IdcProjectedTaskArtifactBinding,
  type IdcProjectedTaskBinding,
  type IdcProjectedTaskPayload,
  type IdcProjectedTaskUpsertInput,
  getIdcProjectedTaskRunId,
  isIdcProjectedTaskPayload,
  toSerializableIdcProjectedTask,
  toIdcProjectedTaskPayload,
  buildCancelTaskActionPlan,
  buildClearCompletedTaskPlan,
  buildBackgroundTaskFailureUpdateView,
  buildRemoveTaskActionPlan,
  buildRetryTaskActionPlan,
  buildTaskResultOpenPlan,
  buildViewTaskResultActionPlan,
  createBackgroundTaskViewFromToolResultData,
  filterTasksForConversation,
  getTaskConversationId,
  getTaskResultUrl,
  matchesTaskConversation,
  mergeBackgroundTaskProgressView,
  runCancelTaskRuntime,
  runClearCompletedTasksRuntime,
  runRemoveTaskRuntime,
  runRetryTaskRuntime,
  runSendTasksRuntime,
  runViewTaskResultRuntime,
  toBackgroundTaskView,
  toBackgroundTaskViewStatus,
  toBackgroundTaskViewType,
  type CancelTaskActionPlan,
  type ClearCompletedTaskPlan,
  type RemoveTaskPlan,
  type RetryTaskPlan,
  type ConversationTasksRuntimeInput,
  type TaskActionRejectPlan,
  type TaskActionNoopPlan,
  type TaskActionRejectReason,
  type TaskMediaCandidate,
  type TaskRuntimeAction,
  type TaskRuntimeDeps,
  type TaskRuntimeEffects,
  type TaskRuntimeInput,
  type TaskRuntimeMediaGateway,
  type TaskRuntimeMessage,
  type TaskRuntimeResult,
  type TaskRuntimeTaskManager,
  type TaskResultOpenPlan,
  type ViewTaskResultPlan,
  // Re-exported types from shared
  type Task,
  type TaskType,
  type TaskStatus,
  type TaskInput,
  type TaskOutput,
  type TaskProgressCallback,
  type ITaskManager,
  type ITaskStorage,
  type ITaskRecoveryStorage,
  type TaskRecoveryInfo,
  type SerializableTask,
  type TaskExecutor,
  type BackgroundTaskView,
  type BackgroundTaskProgressPatch,
  type BackgroundTaskFailureUpdateOptions,
  type BackgroundTaskToolResultProjectionOptions,
  type BackgroundTaskViewProjectorOptions,
  type BackgroundTaskViewStatus,
  type BackgroundTaskViewType,
} from './task';

// Export commands (builtin slash commands)
export {
  // Types
  type BuiltinCommandName,
  type BuiltinCommand,
  type CommandCategory,
  type CommandContext,
  type CommandResult,
  type CommandAction,
  type CommandHandler,
  type CommandHandlerRegistration,
  type SlashCommandSurface,
  type SlashCommandSkillLike,
  type SlashCommandCatalogEntry,
  type BuildExtensionCommandHostEffectPlanInput,
  type BuildExtensionCommandResultPayloadInput,
  type BuildExtensionSkillCommandResultPayloadInput,
  type ExtensionCommandHostEffect,
  type ExtensionCommandHostEffectPlan,
  type ExtensionCommandConversationSummary,
  type ExtensionCommandConversationSummarySource,
  type ExtensionCommandResultPayload,
  type ExtensionSkillCommandResultStatus,
  type ExtensionSlashCommandContextManager,
  type ExtensionSlashCommandConversationSource,
  type ExtensionSlashCommandExecutionDispatch,
  type ExtensionSlashCommandPlanModeSource,
  type ExtensionSlashCommandRuntimeDeps,
  type ExtensionSlashCommandRuntimeEffects,
  type ExtensionSlashCommandRuntimeInput,
  type ExtensionSlashCommandRuntimeResult,
  type ExtensionSlashCommandSettingsSource,
  type ExtensionSlashCommandSkillSource,
  // Constants
  COMMAND_ALIASES,
  BUILTIN_COMMANDS,
  // Functions
  buildExtensionCommandConversationSummaries,
  buildExtensionCommandHostEffectPlan,
  buildExtensionCommandResultPayload,
  buildExtensionSkillCommandResultPayload,
  buildExtensionSlashStatusPayload,
  runExtensionSlashCommandRuntime,
  resolveCommandName,
  normalizeSlashCommandName,
  parseBuiltinCommandArgs,
  shouldExecutePlanPromptAfterToggle,
  listSlashCommandCatalog,
  resolveSlashCommandCatalogEntry,
  getCliCommands,
  getExtensionCommands,
  getBuiltinCommand,
  isBuiltinCommand,
  getAllCommandNames,
  // Handlers
  handleHelp,
  handleStatus,
  handleClear,
  handleExit,
  handleConfig,
  handleModel,
  handleSettings,
  handlePermissions,
  handleInit,
  handleNew,
  handleResume,
  handleCompact,
  handlePlan,
  handleSkills,
  handleCommands,
  handleTools,
  handleTasks,
  handleMcp,
  // Utilities
  generateCliHelpText,
  generateExtensionHelpText,
  generateCliStatusText,
  generateExtensionStatusData,
  // Executor
  parseSlashCommand,
  isSlashCommand,
  executeBuiltinCommand,
  executeSlashCommand,
  getCommandHandler,
} from './commands';

// Export input processing
export {
  InputProcessor,
  createInputProcessor,
  NodeFileReader,
  createNodeFileReader,
  VSCodeFileReader,
  createVSCodeFileReader,
  type VSCodeWorkspaceAPI,
  type FileReference,
  type ProcessedInput,
  type InputProcessorOptions,
  type IFileReader,
  type IInputProcessor,
} from './input';

// Export workspace/content layout helpers
export {
  NEKO_AGENTS_FILE_NAME,
  NEKO_CONTENT_DIR,
  NEKO_CONTENT_SUBDIRS,
  resolveAgentsFile,
  resolveNekoContentDir,
  resolvePersonalAgentsFile,
  resolvePersonalNekoContentDir,
  resolveProjectAgentsFile,
  resolveProjectNekoContentDir,
  type NekoContentSource,
  type NekoContentSubdir,
} from './workspace';
