/**
 * Plan markdown parser — single source of truth for plan parsing
 *
 * Parses markdown plan content (generated by ExitPlanMode tool) into
 * a structured Plan object with steps extracted from ## / ### headings.
 */

import type { Plan, PlanStep } from './types';

/**
 * Parse plan markdown content into a structured Plan object.
 *
 * Extracts steps from ## and ### headings. Content between headings
 * is collected as the step description. If no headings are found,
 * the entire content becomes a single step.
 */
export function parsePlanMarkdown(markdown: string, planId: string, title: string): Plan {
  const lines = markdown.split('\n');
  const steps: PlanStep[] = [];
  let currentStep: string[] = [];
  let stepIndex = 0;

  for (const line of lines) {
    const headerMatch = line.match(/^#{2,3}\s+(.+)$/);
    if (headerMatch) {
      if (currentStep.length > 0) {
        steps.push({
          id: `${planId}-step-${stepIndex}`,
          description: currentStep.join('\n').trim(),
          status: 'pending',
        });
        stepIndex++;
      }
      currentStep = [headerMatch[1]];
    } else if (line.trim()) {
      currentStep.push(line);
    }
  }

  if (currentStep.length > 0) {
    steps.push({
      id: `${planId}-step-${stepIndex}`,
      description: currentStep.join('\n').trim(),
      status: 'pending',
    });
  }

  // Fallback: if no headings found, treat entire content as one step
  if (steps.length === 0) {
    steps.push({
      id: `${planId}-step-0`,
      description: markdown.trim(),
      status: 'pending',
    });
  }

  return { id: planId, title, steps, status: 'pending' };
}
