import type { NodeTypeDescriptorRegistry } from '../../components/nodes/nodeTypeDescriptor';
import {
  ArtboardNodeIcon,
  CanvasEmbedNodeIcon,
  DocumentNodeIcon,
  GalleryNodeIcon,
  ModelNodeIcon,
  ProjectNodeIcon,
  SceneNodeIcon,
  ScriptNodeIcon,
  ShotNodeIcon,
  StoryboardNodeIcon,
  TableNodeIcon,
} from './icons';

export function createStoryboardNodeTypeDescriptors(): NodeTypeDescriptorRegistry {
  return {
    storyboard: {
      type: 'storyboard',
      labelKey: 'node.storyboard',
      icon: StoryboardNodeIcon,
      tagLabel: 'BOARD',
      tagColor: '#f59e0b',
      defaultSize: { width: 240, height: 160 },
      presentation: 'structured',
    },
    artboard: {
      type: 'artboard',
      labelKey: 'node.artboard',
      icon: ArtboardNodeIcon,
      tagLabel: 'ARTBOARD',
      tagColor: '#a855f7',
      defaultSize: { width: 640, height: 360 },
      presentation: 'structured',
    },
    table: {
      type: 'table',
      labelKey: 'node.table',
      icon: TableNodeIcon,
      tagLabel: 'TABLE',
      tagColor: '#0ea5e9',
      defaultSize: { width: 660, height: 400 },
      presentation: 'structured',
    },
    shot: {
      type: 'shot',
      labelKey: 'node.shot',
      icon: ShotNodeIcon,
      tagLabel: 'SHOT',
      tagColor: '#ef4444',
      defaultSize: { width: 220, height: 200 },
      presentation: 'structured',
    },
    scene: {
      type: 'scene',
      labelKey: 'node.sceneGroup',
      icon: SceneNodeIcon,
      tagLabel: 'SCENE',
      tagColor: '#10b981',
      defaultSize: { width: 640, height: 400 },
      presentation: 'structured',
    },
    gallery: {
      type: 'gallery',
      labelKey: 'node.gallery',
      icon: GalleryNodeIcon,
      tagLabel: 'GALLERY',
      tagColor: '#8b5cf6',
      defaultSize: { width: 290, height: 360 },
      presentation: 'structured',
    },
    script: {
      type: 'script',
      labelKey: 'node.script',
      icon: ScriptNodeIcon,
      tagLabel: 'SCRIPT',
      tagColor: '#10b981',
      defaultSize: { width: 280, height: 220 },
      presentation: 'foundational',
    },
    document: {
      type: 'document',
      labelKey: 'node.document',
      icon: DocumentNodeIcon,
      tagLabel: 'DOC',
      tagColor: '#64748b',
      defaultSize: { width: 220, height: 280 },
      presentation: 'foundational',
    },
    model: {
      type: 'model',
      labelKey: 'node.model',
      icon: ModelNodeIcon,
      tagLabel: 'MODEL',
      tagColor: '#14b8a6',
      defaultSize: { width: 240, height: 160 },
      presentation: 'structured',
    },
    'canvas-embed': {
      type: 'canvas-embed',
      labelKey: 'node.canvasEmbed',
      icon: CanvasEmbedNodeIcon,
      tagLabel: 'CANVAS',
      tagColor: '#6366f1',
      defaultSize: { width: 260, height: 180 },
      presentation: 'structured',
    },
    project: {
      type: 'project',
      labelKey: 'node.project',
      icon: ProjectNodeIcon,
      tagLabel: 'PROJECT',
      tagColor: '#d946ef',
      defaultSize: { width: 260, height: 180 },
      presentation: 'structured',
    },
  };
}
