import type { NodeTypeDescriptorRegistry } from '../../components/nodes/nodeTypeDescriptor';

export function createStoryboardNodeTypeDescriptors(): NodeTypeDescriptorRegistry {
  return {
    storyboard: {
      type: 'storyboard',
      labelKey: 'node.storyboard',
      icon: '\u{1F3AC}',
      tagLabel: 'BOARD',
      tagColor: '#f59e0b',
      defaultSize: { width: 240, height: 160 },
    },
    artboard: {
      type: 'artboard',
      labelKey: 'node.artboard',
      icon: '\u{1F5BC}',
      tagLabel: 'ARTBOARD',
      tagColor: '#a855f7',
      defaultSize: { width: 640, height: 360 },
    },
    table: {
      type: 'table',
      labelKey: 'node.table',
      icon: '\u{1F4CA}',
      tagLabel: 'TABLE',
      tagColor: '#0ea5e9',
      defaultSize: { width: 660, height: 400 },
    },
    shot: {
      type: 'shot',
      labelKey: 'node.shot',
      icon: '\u{1F3AC}',
      tagLabel: 'SHOT',
      tagColor: '#ef4444',
      defaultSize: { width: 220, height: 200 },
    },
    scene: {
      type: 'scene',
      labelKey: 'node.sceneGroup',
      icon: '\u{1F39E}',
      tagLabel: 'SCENE',
      tagColor: '#10b981',
      defaultSize: { width: 640, height: 400 },
    },
    gallery: {
      type: 'gallery',
      labelKey: 'node.gallery',
      icon: '\u{1F5BC}',
      tagLabel: 'GALLERY',
      tagColor: '#8b5cf6',
      defaultSize: { width: 290, height: 360 },
    },
    script: {
      type: 'script',
      labelKey: 'node.script',
      icon: '\u{1F4C4}',
      tagLabel: 'SCRIPT',
      tagColor: '#10b981',
      defaultSize: { width: 280, height: 220 },
    },
    document: {
      type: 'document',
      labelKey: 'node.document',
      icon: '\u{1F4DA}',
      tagLabel: 'DOC',
      tagColor: '#64748b',
      defaultSize: { width: 220, height: 280 },
    },
    model: {
      type: 'model',
      labelKey: 'node.model',
      icon: '\u{1F9E0}',
      tagLabel: 'MODEL',
      tagColor: '#14b8a6',
      defaultSize: { width: 240, height: 160 },
    },
    'canvas-embed': {
      type: 'canvas-embed',
      labelKey: 'node.canvasEmbed',
      icon: '\u{1F5C2}',
      tagLabel: 'CANVAS',
      tagColor: '#6366f1',
      defaultSize: { width: 260, height: 180 },
    },
    project: {
      type: 'project',
      labelKey: 'node.project',
      icon: '\u{1F4E6}',
      tagLabel: 'PROJECT',
      tagColor: '#d946ef',
      defaultSize: { width: 260, height: 180 },
    },
  };
}
