/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Probe media file metadata via the unified API
 *
 * Maps to: videos:probe
 *
 * Returns JSON ActionResponse with media metadata (streams, duration, format, etc.)
 */
export declare function bridgeProbeMedia(path: string): Promise<string>
/**
 * Extract all subtitle tracks from a media file via the unified API
 *
 * Maps to: videos:extract (type=subtitles)
 *
 * Returns JSON ActionResponse with extracted subtitle tracks
 */
export declare function bridgeExtractSubtitles(path: string): Promise<string>
/**
 * Extract a single frame from video via the unified API
 *
 * Maps to: videos:capture
 *
 * Returns JSON ActionResponse with base64-encoded frame data
 */
export declare function bridgeExtractFrame(path: string, time: number, quality?: number | undefined | null, width?: number | undefined | null, height?: number | undefined | null): Promise<string>
/**
 * Get GPU information via the unified API
 *
 * Maps to: nodes:gpu
 *
 * Returns JSON ActionResponse with GPU device info
 */
export declare function bridgeGpuInfo(): Promise<string>
/**
 * Get audio file information via the unified API
 *
 * Maps to: audios:probe
 *
 * Returns JSON ActionResponse with audio metadata (codec, sample rate, channels, etc.)
 */
export declare function bridgeAudioInfo(path: string): Promise<string>
/**
 * Generate waveform data for a media file via the unified API
 *
 * Maps to: videos:waveform
 *
 * Returns JSON ActionResponse with waveform sample data
 */
export declare function bridgeGenerateWaveform(path: string): Promise<string>
/**
 * Get keyframe timestamps from a video file via the unified API
 *
 * Maps to: videos:keyframes
 *
 * Returns JSON ActionResponse with keyframe timestamp list
 */
export declare function bridgeGetKeyframes(path: string): Promise<string>
/**
 * Encode RGBA pixel data to JPEG via the unified API
 *
 * Maps to: images:encode
 *
 * Returns JSON ActionResponse with base64-encoded JPEG data
 */
export declare function bridgeEncodeJpeg(rgbaDataBase64: string, width: number, height: number, quality?: number | undefined | null): Promise<string>
/** Create preset animations */
export declare function createFadeInAnimation(id: string, targetId: string, duration: number): AnimationSession
export declare function createFadeOutAnimation(id: string, targetId: string, duration: number): AnimationSession
export declare function createSlideInLeftAnimation(id: string, targetId: string, duration: number, distance: number): AnimationSession
export declare function createZoomInAnimation(id: string, targetId: string, duration: number): AnimationSession
export declare function createBounceAnimation(id: string, targetId: string, duration: number, height: number): AnimationSession
export declare function createPulseAnimation(id: string, targetId: string, duration: number, scaleFactor: number): AnimationSession
/** Frame server configuration for N-API */
export interface JsFrameServerConfig {
  /** Preferred port (0 for auto-assign) */
  port?: number
  /** Maximum frame buffer size */
  maxBufferSize?: number
  /** JPEG quality (1-100) */
  jpegQuality?: number
}
/** Frame server statistics */
export interface JsFrameServerStats {
  framesSent: number
  isRunning: boolean
}
/** Configuration for preview pipeline */
export interface JsPreviewPipelineConfig {
  /** Output width */
  width: number
  /** Output height */
  height: number
  /** Frame rate */
  fps: number
  /** Bitrate in bits per second (default: 2 Mbps) */
  bitrate?: number
  /** GOP size (keyframe interval, default: 30) */
  gopSize?: number
}
/** Encoded preview frame (H.264 NAL unit) */
export interface JsPreviewFrame {
  /** H.264 NAL unit data */
  data: Buffer
  /** Presentation timestamp in microseconds */
  pts: number
  /** Decode timestamp in microseconds */
  dts: number
  /** Whether this is a keyframe (IDR) */
  isKeyframe: boolean
}
/** Probe media file and extract metadata */
export declare function probeMedia(path: string): JsProbeMediaInfo
/** Extracted frame with JPEG data for JavaScript */
export interface JsExtractedFrameWithData {
  /** Frame timestamp in seconds */
  time: number
  /** Frame width */
  width: number
  /** Frame height */
  height: number
  /** JPEG image data */
  data: Buffer
}
/** Extract all subtitle tracks from a media file */
export declare function extractAllSubtitles(path: string): Array<JsExtractedSubtitleTrack>
/**
 * Encode RGBA buffer to JPEG using FFmpeg's MJPEG encoder
 *
 * This provides a zero-copy alternative to sharp for JPEG encoding.
 * The input must be RGBA format (4 bytes per pixel).
 *
 * # Arguments
 * * `rgba_data` - RGBA pixel data buffer
 * * `width` - Image width in pixels
 * * `height` - Image height in pixels
 * * `quality` - JPEG quality (1-100, higher is better quality, default 85)
 *
 * # Returns
 * * JPEG image data as Buffer
 */
export declare function encodeJpeg(rgbaData: Buffer, width: number, height: number, quality?: number | undefined | null): Buffer
/** Output format for frame extraction */
export const enum FrameFormat {
  /** JPEG image (default) - universal compatibility */
  Jpeg = 'Jpeg',
  /** H.264 I-frame - hardware accelerated, smaller size, requires WebCodecs to decode */
  H264 = 'H264'
}
/**
 * Extract a single frame from video
 *
 * Uses hardware-accelerated decoding (VideoToolbox/VAAPI/D3D11VA).
 * Default output is JPEG for universal compatibility.
 * Use format="h264" for H.264 I-frame output (requires WebCodecs to decode).
 */
export declare function extractFrame(source: string, time: number, quality?: number | undefined | null, format?: FrameFormat | undefined | null): Buffer
/** Composite layer input for frame extraction NAPI */
export interface JsExtractCompositeLayer {
  /** Source video file path */
  source: string
  /** Time in seconds to extract frame */
  time: number
  /** Layer opacity (0.0-1.0, default 1.0) */
  opacity?: number
  /** Blend mode (default "normal") */
  blendMode?: string
  /** X position */
  x?: number
  /** Y position */
  y?: number
  /** Scale X (default 1.0) */
  scaleX?: number
  /** Scale Y (default 1.0) */
  scaleY?: number
  /** Rotation in degrees */
  rotation?: number
}
/** Composite request for frame extraction NAPI */
export interface JsCompositeFrameRequest {
  /** Output width */
  width: number
  /** Output height */
  height: number
  /** Layers to composite (bottom to top) */
  layers: Array<JsExtractCompositeLayer>
  /** Background color [r, g, b, a] (0.0-1.0) */
  background?: Array<number>
  /** JPEG quality (1-100, default 85) */
  quality?: number
}
/**
 * Composite multiple video frames into a single JPEG image
 *
 * Uses GPU-accelerated decoding and compositing for optimal performance.
 * Supports multiple blend modes and 2D transforms.
 */
export declare function compositeFrame(request: JsCompositeFrameRequest): Buffer
/** GPU information for JavaScript */
export interface JsGpuInfo {
  name: string
  vendor: string
  backend: string
  deviceType: string
}
/** Effect parameters from JavaScript */
export interface JsEffectParams {
  brightness?: number
  contrast?: number
  saturation?: number
  exposure?: number
  gamma?: number
  hueShift?: number
  vibrance?: number
  temperature?: number
  tint?: number
  highlights?: number
  shadows?: number
  whites?: number
  blacks?: number
}
/** Blur parameters from JavaScript */
export interface JsBlurParams {
  /** Blur type: "box", "gaussian", "directional", "radial", "zoom" */
  blurType?: string
  /** Blur radius in pixels (1-100) */
  radius?: number
  /** Direction X for directional blur (-1.0 to 1.0) */
  directionX?: number
  /** Direction Y for directional blur (-1.0 to 1.0) */
  directionY?: number
  /** Center X for radial/zoom blur (0.0 to 1.0) */
  centerX?: number
  /** Center Y for radial/zoom blur (0.0 to 1.0) */
  centerY?: number
  /** Blur strength (0.0 to 1.0) */
  strength?: number
  /** Number of samples for quality (8-64) */
  samples?: number
}
/** Sharpen parameters from JavaScript */
export interface JsSharpenParams {
  /** Sharpen amount (0.0 to 5.0) */
  amount?: number
  /** Radius for unsharp mask (0.5 to 5.0) */
  radius?: number
  /** Threshold to avoid sharpening noise (0.0 to 1.0) */
  threshold?: number
}
/** Vignette effect parameters from JavaScript */
export interface JsVignetteParams {
  /** Vignette amount/intensity (0.0 to 1.0) */
  amount?: number
  /** Radius from center where vignette starts (0.0 to 2.0) */
  radius?: number
  /** Softness/feather of the vignette edge (0.0 to 1.0) */
  softness?: number
  /** Roundness of the vignette (0.0 = oval, 1.0 = circular) */
  roundness?: number
}
/** Film grain effect parameters from JavaScript */
export interface JsFilmGrainParams {
  /** Grain amount/intensity (0.0 to 1.0) */
  amount?: number
  /** Grain size multiplier (0.5 to 3.0) */
  size?: number
  /** Time value for animation (used as random seed) */
  time?: number
  /** Color vs monochrome grain (0.0 = mono, 1.0 = color) */
  colorAmount?: number
}
/** Glow/Bloom effect parameters from JavaScript */
export interface JsGlowParams {
  /** Glow intensity (0.0 to 2.0) */
  intensity?: number
  /** Brightness threshold for glow (0.0 to 1.0) */
  threshold?: number
  /** Blur radius for glow (1.0 to 50.0) */
  radius?: number
}
/** Chromatic aberration effect parameters from JavaScript */
export interface JsChromaticAberrationParams {
  /** Aberration amount/offset (0.0 to 0.1) */
  amount?: number
  /** Angle of aberration in radians */
  angle?: number
  /** Center X (0.0 to 1.0) */
  centerX?: number
  /** Center Y (0.0 to 1.0) */
  centerY?: number
}
/** Transition effect parameters from JavaScript */
export interface JsTransitionParams {
  /**
   * Transition type: "fade", "wipe_left", "wipe_right", "wipe_up", "wipe_down",
   * "iris_circle", "iris_rectangle", "clock", "slide_left", "slide_right",
   * "zoom_in", "zoom_out", "dissolve", "pixelate", "ripple", "swirl", "glitch", "flash"
   */
  transitionType?: string
  /** Transition progress (0.0 to 1.0) */
  progress?: number
  /** Edge feather/softness (0.0 to 1.0) */
  feather?: number
  /** Center X for radial transitions (0.0 to 1.0) */
  centerX?: number
  /** Center Y for radial transitions (0.0 to 1.0) */
  centerY?: number
  /** Angle for directional transitions (radians) */
  angle?: number
}
/** Decoder configuration from JavaScript */
export interface JsDecoderConfig {
  path: string
  hwAccel?: string
  outputFormat?: string
}
/** Frame data for JavaScript */
export interface JsFrameData {
  width: number
  height: number
  format: string
  data: Buffer
  timestamp: number
  isKeyframe: boolean
}
/** Hardware acceleration info for JavaScript */
export interface JsHwAccelInfo {
  decoders: Array<string>
  encoders: Array<string>
  recommendedDecoder: string
  recommendedEncoder: string
}
/** Texture handle for JavaScript - represents a GPU texture that can be shared */
export interface JsTextureHandle {
  /** Unique texture ID */
  id: number
  /** Texture width */
  width: number
  /** Texture height */
  height: number
  /** Texture format ("rgba8", "bgra8", "nv12") */
  format: string
  /** Shared memory key for cross-process sharing (if available) */
  sharedMemoryKey?: string
  /** Texture generation (incremented on each update) */
  generation: number
}
/** Texture format enum for JavaScript */
export const enum JsTextureFormat {
  /** RGBA 8-bit per channel */
  Rgba8 = 'Rgba8',
  /** BGRA 8-bit per channel */
  Bgra8 = 'Bgra8',
  /** NV12 (Y + UV planes) */
  Nv12 = 'Nv12',
  /** YUV420P (Y + U + V separate planes) */
  Yuv420p = 'Yuv420p'
}
/** Video codec enum for JavaScript */
export const enum JsVideoCodec {
  /** H.264 / AVC */
  H264 = 'H264',
  /** H.265 / HEVC */
  H265 = 'H265',
  /** VP9 */
  Vp9 = 'Vp9',
  /** Apple ProRes */
  ProRes = 'ProRes'
}
/** Container format enum for JavaScript */
export const enum JsContainerFormat {
  /** MP4 container */
  Mp4 = 'Mp4',
  /** Matroska container */
  Mkv = 'Mkv',
  /** WebM container */
  WebM = 'WebM',
  /** QuickTime MOV container */
  Mov = 'Mov'
}
/** Encoder preset enum for JavaScript */
export const enum JsEncoderPreset {
  /** Fastest encoding, lowest quality */
  Ultrafast = 'Ultrafast',
  /** Fast encoding */
  Fast = 'Fast',
  /** Balanced */
  Medium = 'Medium',
  /** Slower encoding, better quality */
  Slow = 'Slow',
  /** Slowest encoding, best quality */
  Veryslow = 'Veryslow'
}
/** Video encoder configuration for JavaScript */
export interface JsEncoderConfig {
  /** Output width */
  width: number
  /** Output height */
  height: number
  /** Frame rate (fps) */
  fps: number
  /** Target bitrate in bits per second */
  bitrate?: number
  /** Video codec ("h264", "h265", "vp9", "prores") */
  codec: string
  /** Encoding preset ("ultrafast", "fast", "medium", "slow", "veryslow") */
  preset?: string
  /** Codec profile (e.g., "high", "main", "baseline") */
  profile?: string
  /** Input pixel format ("rgba", "rgb", "yuv420p", "nv12") */
  pixelFormat?: string
  /**
   * Hardware encoder type ("auto", "videotoolbox", "nvenc", "vaapi", "qsv", "none")
   * If not specified or "none", software encoding is used.
   * "auto" will try to use the best available hardware encoder.
   */
  hwEncoder?: string
}
/** Encoded packet for JavaScript */
export interface JsEncodedPacket {
  /** Encoded data */
  data: Buffer
  /** Presentation timestamp */
  pts: number
  /** Decoding timestamp */
  dts: number
  /** Whether this is a keyframe */
  isKeyframe: boolean
  /** Duration */
  duration: number
}
/** Audio codec enum for JavaScript */
export const enum JsAudioCodec {
  /** AAC */
  Aac = 'Aac',
  /** MP3 */
  Mp3 = 'Mp3',
  /** Opus */
  Opus = 'Opus',
  /** FLAC (lossless) */
  Flac = 'Flac',
  /** PCM (uncompressed) */
  Pcm = 'Pcm'
}
/** Audio sample format enum for JavaScript */
export const enum JsSampleFormat {
  /** Unsigned 8-bit */
  U8 = 'U8',
  /** Signed 16-bit */
  S16 = 'S16',
  /** Signed 32-bit */
  S32 = 'S32',
  /** 32-bit float */
  F32 = 'F32',
  /** 64-bit float */
  F64 = 'F64'
}
/** Audio encoder configuration for JavaScript */
export interface JsAudioEncoderConfig {
  /** Sample rate in Hz */
  sampleRate: number
  /** Number of channels */
  channels: number
  /** Target bitrate in bits per second */
  bitrate?: number
  /** Audio codec ("aac", "mp3", "opus", "flac", "pcm") */
  codec?: string
  /** Sample format ("u8", "s16", "s32", "f32", "f64") */
  sampleFormat?: string
}
/** Audio info for JavaScript */
export interface JsAudioInfo {
  /** Sample rate in Hz */
  sampleRate: number
  /** Number of channels */
  channels: number
  /** Duration in seconds */
  duration: number
  /** Codec name */
  codec: string
  /** Bitrate in bps */
  bitrate: number
  /** Total number of samples */
  totalSamples: number
}
/** Decoded audio frame for JavaScript */
export interface JsAudioFrame {
  /** Audio sample data */
  data: Buffer
  /** Number of samples per channel */
  samples: number
  /** Timestamp in seconds */
  timestamp: number
  /** Sample rate */
  sampleRate: number
  /** Number of channels */
  channels: number
}
/** Encoded audio packet for JavaScript */
export interface JsEncodedAudioPacket {
  /** Encoded data */
  data: Buffer
  /** Presentation timestamp */
  pts: number
  /** Duration */
  duration: number
}
/** Muxer configuration for JavaScript */
export interface JsMuxerConfig {
  /** Output file path */
  outputPath: string
  /** Container format ("mp4", "mkv", "webm", "mov") */
  format: string
}
/** Stream info for JavaScript */
export interface JsStreamInfo {
  /** Stream index */
  index: number
  /** Time base numerator */
  timeBaseNum: number
  /** Time base denominator */
  timeBaseDen: number
}
/** Packet for muxing (video or audio) */
export interface JsMuxerPacket {
  /** Encoded data */
  data: Buffer
  /** Presentation timestamp */
  pts: number
  /** Decoding timestamp */
  dts: number
  /** Duration */
  duration: number
  /** Whether this is a keyframe (video only) */
  isKeyframe: boolean
}
/** Blend mode enum for JavaScript */
export const enum JsBlendMode {
  /** Normal blend */
  Normal = 'Normal',
  /** Multiply */
  Multiply = 'Multiply',
  /** Screen */
  Screen = 'Screen',
  /** Overlay */
  Overlay = 'Overlay',
  /** Darken */
  Darken = 'Darken',
  /** Lighten */
  Lighten = 'Lighten',
  /** Color Dodge */
  ColorDodge = 'ColorDodge',
  /** Color Burn */
  ColorBurn = 'ColorBurn',
  /** Hard Light */
  HardLight = 'HardLight',
  /** Soft Light */
  SoftLight = 'SoftLight',
  /** Difference */
  Difference = 'Difference',
  /** Exclusion */
  Exclusion = 'Exclusion',
  /** Add */
  Add = 'Add',
  /** Subtract */
  Subtract = 'Subtract'
}
/** 2D Transform for JavaScript */
export interface JsTransform2D {
  /** Position X (pixels) */
  x: number
  /** Position Y (pixels) */
  y: number
  /** Scale X (1.0 = 100%) */
  scaleX: number
  /** Scale Y (1.0 = 100%) */
  scaleY: number
  /** Rotation (degrees) */
  rotation: number
  /** Anchor point X (0.0 = left, 0.5 = center, 1.0 = right) */
  anchorX: number
  /** Anchor point Y (0.0 = top, 0.5 = center, 1.0 = bottom) */
  anchorY: number
}
/** Composite layer for JavaScript */
export interface JsCompositeLayer {
  /** Layer pixel data (RGBA or YUV420P depending on pixel_format) */
  data: Buffer
  /** Layer width */
  width: number
  /** Layer height */
  height: number
  /** Pixel format: "rgba" (default) or "yuv420p" */
  pixelFormat?: string
  /** Transform (optional, defaults to identity) */
  transform?: JsTransform2D
  /** Opacity (0.0 - 1.0) */
  opacity?: number
  /** Blend mode */
  blendMode?: string
  /** Z-index (lower = bottom) */
  zIndex?: number
  /** Mask data (optional, grayscale) */
  mask?: Buffer
  /** Invert mask */
  maskInverted?: boolean
}
/** Composite result for JavaScript */
export interface JsCompositeResult {
  /** Output pixel data (RGBA) */
  data: Buffer
  /** Output width */
  width: number
  /** Output height */
  height: number
  /** Compositing time in milliseconds */
  timeMs: number
  /** Number of layers composited */
  layerCount: number
}
/** Easing type enum for JavaScript */
export const enum JsEasingType {
  Linear = 'Linear',
  EaseInQuad = 'EaseInQuad',
  EaseOutQuad = 'EaseOutQuad',
  EaseInOutQuad = 'EaseInOutQuad',
  EaseInCubic = 'EaseInCubic',
  EaseOutCubic = 'EaseOutCubic',
  EaseInOutCubic = 'EaseInOutCubic',
  EaseInQuart = 'EaseInQuart',
  EaseOutQuart = 'EaseOutQuart',
  EaseInOutQuart = 'EaseInOutQuart',
  EaseInQuint = 'EaseInQuint',
  EaseOutQuint = 'EaseOutQuint',
  EaseInOutQuint = 'EaseInOutQuint',
  EaseInSine = 'EaseInSine',
  EaseOutSine = 'EaseOutSine',
  EaseInOutSine = 'EaseInOutSine',
  EaseInExpo = 'EaseInExpo',
  EaseOutExpo = 'EaseOutExpo',
  EaseInOutExpo = 'EaseInOutExpo',
  EaseInCirc = 'EaseInCirc',
  EaseOutCirc = 'EaseOutCirc',
  EaseInOutCirc = 'EaseInOutCirc',
  EaseInBack = 'EaseInBack',
  EaseOutBack = 'EaseOutBack',
  EaseInOutBack = 'EaseInOutBack',
  EaseInElastic = 'EaseInElastic',
  EaseOutElastic = 'EaseOutElastic',
  EaseInOutElastic = 'EaseInOutElastic',
  EaseInBounce = 'EaseInBounce',
  EaseOutBounce = 'EaseOutBounce',
  EaseInOutBounce = 'EaseInOutBounce'
}
/** Interpolation mode enum for JavaScript */
export const enum JsInterpolationMode {
  /** Linear interpolation */
  Linear = 'Linear',
  /** Step/hold interpolation */
  Step = 'Step',
  /** Smooth interpolation */
  Smooth = 'Smooth'
}
/** Animatable value for JavaScript */
export interface JsAnimatableValue {
  /** Value type: "number", "point2d", "point3d", "color", "bool" */
  valueType: string
  /** For number type */
  number?: number
  /** For point2d type */
  x?: number
  y?: number
  /** For point3d type */
  z?: number
  /** For color type */
  r?: number
  g?: number
  b?: number
  a?: number
  /** For bool type */
  boolValue?: boolean
}
/** Keyframe for JavaScript */
export interface JsKeyframe {
  /** Time in seconds */
  time: number
  /** Value at this keyframe */
  value: JsAnimatableValue
  /** Easing type (optional, defaults to linear) */
  easing?: string
  /** Interpolation mode (optional, defaults to linear) */
  interpolation?: string
}
/** Keyframe track for JavaScript */
export interface JsKeyframeTrack {
  /** Property name */
  property: string
  /** Keyframes */
  keyframes: Array<JsKeyframe>
  /** Default value (optional) */
  defaultValue?: JsAnimatableValue
}
/** Evaluated properties for JavaScript */
export interface JsEvaluatedProperties {
  /** Property name -> value mapping */
  values: Record<string, JsAnimatableValue>
}
/** Export pipeline configuration for JavaScript */
export interface JsPipelineConfig {
  /** Output file path */
  outputPath: string
  /** Container format ("mp4", "mkv", "webm", "mov") */
  container?: string
  /** Video encoder configuration */
  encoderConfig: JsEncoderConfig
  /** Compose stage buffer size (default: 3) */
  composeBufferSize?: number
  /** Encode stage buffer size (default: 4) */
  encodeBufferSize?: number
  /** Mux stage buffer size (default: 8) */
  muxBufferSize?: number
  /** Total expected frames (for progress reporting) */
  totalFrames?: number
}
/** Export pipeline progress for JavaScript */
export interface JsPipelineProgress {
  /** Frames submitted to pipeline */
  framesSubmitted: number
  /** Frames composited (GPU) */
  framesComposited: number
  /** Frames encoded */
  framesEncoded: number
  /** Frames muxed (written to file) */
  framesMuxed: number
  /** Total frames expected */
  totalFrames: number
  /** Progress ratio (0.0 - 1.0) */
  progressRatio: number
  /** Whether pipeline is complete */
  isComplete: boolean
  /** Error message if pipeline failed */
  error?: string
}
/** Pipeline frame input for JavaScript */
export interface JsPipelineFrame {
  /** Frame index (sequential, for ordering) */
  index: number
  /** Presentation timestamp (time base units) */
  pts: number
  /** Layers to composite */
  layers: Array<JsCompositeLayer>
  /** Output width */
  outputWidth: number
  /** Output height */
  outputHeight: number
  /** Background color [r, g, b, a] (0.0-1.0) */
  backgroundColor?: Array<number>
}
/** Probed media information for JavaScript */
export interface JsProbeMediaInfo {
  /** Duration in seconds */
  duration: number
  /** Video width */
  width: number
  /** Video height */
  height: number
  /** Frame rate */
  fps: number
  /** Video codec name */
  codec: string
  /** Container format */
  format: string
  /** Video bitrate (bps) */
  bitrate?: number
  /** Has audio stream */
  hasAudio: boolean
  /** Audio codec name */
  audioCodec?: string
  /** Audio sample rate */
  audioSampleRate?: number
  /** Audio channels */
  audioChannels?: number
  /** Audio bitrate (bps) */
  audioBitrate?: number
  /** Has subtitle streams */
  hasSubtitles: boolean
  /** Subtitle stream info */
  subtitleStreams: Array<JsProbeSubtitleStream>
}
/** Subtitle stream info for JavaScript */
export interface JsProbeSubtitleStream {
  /** Stream index */
  index: number
  /** Codec name */
  codec: string
  /** Language code */
  language?: string
  /** Stream title */
  title?: string
  /** Is default stream */
  isDefault: boolean
  /** Is forced stream */
  isForced: boolean
}
/** Subtitle cue for JavaScript */
export interface JsSubtitleCue {
  /** Unique identifier */
  id: string
  /** Start time in seconds */
  startTime: number
  /** End time in seconds */
  endTime: number
  /** Subtitle text */
  text: string
}
/** Extracted subtitle track for JavaScript */
export interface JsExtractedSubtitleTrack {
  /** Stream index */
  streamIndex: number
  /** Language code */
  language?: string
  /** Track title */
  title?: string
  /** Is default track */
  isDefault: boolean
  /** Subtitle cues */
  cues: Array<JsSubtitleCue>
}
/**
 * NativeEngine - Main entry point for all engine operations
 *
 * This class provides a unified interface to the Neko Engine through
 * the ActionRequest/ActionResponse protocol.
 *
 * It also manages an optional embedded HTTP/WebSocket server for
 * per-stream frame delivery to webview consumers.
 */
export declare class NativeEngine {
  /**
   * Create a new NativeEngine instance
   *
   * This initializes the engine with GPU support if available.
   */
  static create(): Promise<NativeEngine>
  /**
   * Dispatch an action request
   *
   * This is the main entry point for all operations.
   * Takes a JSON string representing an ActionRequest and returns
   * a JSON string representing an ActionResponse.
   */
  dispatch(requestJson: string): Promise<string>
  /**
   * Dispatch an action request with typed parameters
   *
   * Convenience method that takes individual parameters instead of JSON.
   */
  dispatchAction(group: string, action: string, id?: string | undefined | null, options?: string | undefined | null): Promise<string>
  /** Check if GPU is available */
  hasGpu(): boolean
  /** Get list of supported action groups */
  groups(): Array<string>
  /** Get list of supported actions for a group */
  actions(group: string): Array<string> | null
  /** Get system health status */
  health(): Promise<string>
  /** Get system metrics (CPU, memory, GPU usage) */
  metrics(): Promise<string>
  /** Get GPU information */
  gpuInfo(): Promise<string>
  /** Probe a video file for metadata */
  probeVideo(source: string): Promise<string>
  /** List all active tasks */
  listTasks(): Promise<string>
  /** Get task progress */
  getTaskProgress(taskId: string): Promise<string>
  /** Cancel a task */
  cancelTask(taskId: string): Promise<string>
  /**
   * Capture a single frame from video
   *
   * Returns JSON with base64-encoded frame data
   */
  captureFrame(source: string, time: number, quality?: number | undefined | null, format?: string | undefined | null): Promise<string>
  /**
   * Start the embedded HTTP/WebSocket server for frame streaming
   *
   * The server provides:
   * - `ws://127.0.0.1:{port}/v1/streams/{stream_id}` — per-stream WebSocket
   * - `POST http://127.0.0.1:{port}/v1/dispatch` — ActionRequest dispatch
   * - `GET http://127.0.0.1:{port}/health` — health check
   *
   * Returns the actual bound port (useful when port=0 for auto-assign).
   */
  startFrameServer(port?: number | undefined | null): Promise<number>
  /** Stop the embedded HTTP/WebSocket server */
  stopFrameServer(): Promise<void>
  /** Get the frame server port, or null if not running */
  getFrameServerPort(): number | null
  /**
   * Create a stream and return WebSocket endpoint info (JSON)
   *
   * Convenience method that dispatches `streams:create` and fills in the
   * `wsPort` field from the running frame server.
   */
  createStream(sessionId: string, resourceId: string, width?: number | undefined | null, height?: number | undefined | null, fps?: number | undefined | null): Promise<string>
  /**
   * Push a frame to a specific stream (per-stream, replaces FrameServerSession.pushFrame)
   *
   * This is a synchronous method optimized for high-frequency calls (30-60fps).
   * It uses `try_read()` on the stream registry to avoid async overhead.
   */
  pushStreamFrame(streamId: string, data: Buffer, width: number, height: number, timestamp: number, format?: string | undefined | null): void
}
/** High-performance media processor with GPU acceleration */
export declare class MediaProcessor {
  /** Create a new MediaProcessor instance */
  static create(): Promise<MediaProcessor>
  /** Get GPU information */
  getGpuInfo(): JsGpuInfo
  /** Detect available hardware acceleration */
  detectHwAccel(): JsHwAccelInfo
  /**
   * Decode a single frame using true zero-copy (macOS only)
   *
   * This method uses IOSurface → Metal → wgpu path to avoid any CPU memory copy.
   * Returns RGBA frame data after GPU color conversion.
   */
  decodeFrameZerocopy(config: JsDecoderConfig, timeSeconds: number): JsFrameData
  /**
   * Decode a single frame from a video file (GPU only)
   *
   * Uses hardware decoding with GPU color conversion.
   * Returns error if decoding fails (frame will be dropped).
   */
  decodeFrame(config: JsDecoderConfig, timeSeconds: number): JsFrameData
  /**
   * Decode a range of frames from a video file (GPU only)
   *
   * Uses hardware decoding with GPU color conversion.
   * Frames that fail to decode are skipped (dropped).
   */
  decodeFrameRange(config: JsDecoderConfig, startTime: number, endTime: number, fps: number): Array<JsFrameData>
  /** Apply GPU effects to a frame */
  applyEffects(frame: JsFrameData, params: JsEffectParams): JsFrameData
  /** Apply blur effect to a frame */
  applyBlur(frame: JsFrameData, params: JsBlurParams): JsFrameData
  /** Apply sharpen effect to a frame */
  applySharpen(frame: JsFrameData, params: JsSharpenParams): JsFrameData
  /** Apply vignette effect to a frame */
  applyVignette(frame: JsFrameData, params: JsVignetteParams): JsFrameData
  /** Apply film grain effect to a frame */
  applyFilmGrain(frame: JsFrameData, params: JsFilmGrainParams): JsFrameData
  /** Apply glow/bloom effect to a frame */
  applyGlow(frame: JsFrameData, params: JsGlowParams): JsFrameData
  /** Apply chromatic aberration effect to a frame */
  applyChromaticAberration(frame: JsFrameData, params: JsChromaticAberrationParams): JsFrameData
  /** Apply transition effect between two frames */
  applyTransition(fromFrame: JsFrameData, toFrame: JsFrameData, params: JsTransitionParams): JsFrameData
  /** Process a frame: decode and apply effects in one call */
  processFrame(config: JsDecoderConfig, timeSeconds: number, params?: JsEffectParams | undefined | null): JsFrameData
  /**
   * Upload a frame to GPU texture and return a handle
   * This enables zero-copy rendering in WebGPU
   */
  uploadToTexture(frame: JsFrameData, format?: JsTextureFormat | undefined | null): JsTextureHandle
  /**
   * Decode a frame directly to GPU texture (zero-copy path)
   * Returns a texture handle instead of raw pixel data
   */
  decodeToTexture(config: JsDecoderConfig, timeSeconds: number): JsTextureHandle
  /**
   * Get texture data back from GPU (for fallback/debugging)
   * This copies data from GPU to CPU, use sparingly
   */
  readTexture(handle: JsTextureHandle): JsFrameData
  /** Clear all textures from the pool */
  clearTexturePool(): void
  /** Get number of textures in the pool */
  texturePoolSize(): number
  /** Release all resources */
  dispose(): void
  /**
   * Convert RGBA frame to NV12 format using GPU compute shader
   *
   * This is the GPU-accelerated version of RGBA to NV12 conversion,
   * suitable for hardware encoder input.
   *
   * @param frame - Input RGBA frame data
   * @param colorSpace - Color space: 0 = BT.601, 1 = BT.709 (default), 2 = BT.2020
   * @returns NV12 frame data (Y plane followed by UV plane)
   */
  rgbaToNv12(frame: JsFrameData, colorSpace?: number | undefined | null): JsFrameData
  /**
   * Encode a single video frame (GPU only)
   *
   * Uses hardware encoder. Returns error if encoding fails.
   */
  encodeVideoFrame(config: JsEncoderConfig, frame: JsFrameData, pts: number): Array<JsEncodedPacket>
  /**
   * Create a stateful video encoder session (GPU only)
   *
   * Uses hardware encoder. Returns error if encoder creation fails.
   */
  createVideoEncoder(config: JsEncoderConfig): VideoEncoderSession
  /** Get audio information from a file */
  getAudioInfo(path: string): JsAudioInfo
  /** Decode audio frame at specific time */
  decodeAudioFrame(path: string, timeSeconds: number): JsAudioFrame
  /** Decode a range of audio frames */
  decodeAudioRange(path: string, startTime: number, endTime: number): Array<JsAudioFrame>
  /** Create a stateful audio decoder session */
  createAudioDecoder(path: string): AudioDecoderSession
  /** Create a stateful audio encoder session */
  createAudioEncoder(config: JsAudioEncoderConfig): AudioEncoderSession
}
/** Animation timeline session for keyframe animations */
export declare class AnimationSession {
  /** Create a new animation session */
  static create(id: string, targetId: string): AnimationSession
  /** Add a keyframe track to the animation */
  addTrack(track: JsKeyframeTrack): void
  /** Evaluate all tracks at given time */
  evaluate(time: number): JsEvaluatedProperties
  /** Get animation duration */
  duration(): number
  /** Set explicit duration */
  setDuration(duration: number): void
  /** Enable/disable looping */
  setLoop(enabled: boolean, count?: number | undefined | null): void
  /** Check if animation is complete at given time */
  isComplete(time: number): boolean
  /** Get number of tracks */
  trackCount(): number
  /** Get all animated properties */
  properties(): Array<string>
}
/** GPU compositor session for multi-layer compositing */
export declare class CompositorSession {
  /** Create a new compositor session */
  static create(): Promise<CompositorSession>
  /** Composite multiple layers into a single output */
  composite(layers: Array<JsCompositeLayer>, outputWidth: number, outputHeight: number, backgroundColor?: Array<number> | undefined | null): JsCompositeResult
  /** Composite a single layer (convenience method) */
  compositeSingle(layer: JsCompositeLayer, outputWidth: number, outputHeight: number): JsCompositeResult
}
/** Stateful audio decoder session */
export declare class AudioDecoderSession {
  /** Get audio info */
  getInfo(): JsAudioInfo
  /** Seek to time position */
  seek(timeSeconds: number): void
  /** Decode next frame */
  decodeNext(): JsAudioFrame | null
  /** Get current position */
  position(): number
  /** Close the decoder */
  close(): void
}
/** Stateful video encoder session (GPU only) */
export declare class VideoEncoderSession {
  /** Check if hardware encoding is active */
  isHwActive(): boolean
  /** Encode a frame */
  encodeFrame(frame: JsFrameData, pts: number): Array<JsEncodedPacket>
  /** Flush encoder and get remaining packets */
  flush(): Array<JsEncodedPacket>
  /** Close the encoder */
  close(): void
}
/** Stateful audio encoder session */
export declare class AudioEncoderSession {
  /** Encode audio samples */
  encodeFrame(data: Buffer, samples: number): Array<JsEncodedAudioPacket>
  /** Flush encoder and get remaining packets */
  flush(): Array<JsEncodedAudioPacket>
  /** Close the encoder */
  close(): void
}
/** Frame server session for streaming video frames via HTTP/WebSocket */
export declare class FrameServerSession {
  /**
   * Start a new frame server with export support
   *
   * This version includes the export API endpoints for compat mode video export:
   * - POST /export/start
   * - POST /export/cancel/:job_id
   * - GET /export/status/:job_id
   * - GET /export/progress (WebSocket)
   */
  static start(config?: JsFrameServerConfig | undefined | null): FrameServerSession
  /** Get the server port */
  getPort(): number
  /** Get the server URL for MJPEG streaming */
  getMjpegUrl(): string
  /** Get the server URL for WebSocket streaming */
  getWebsocketUrl(): string
  /** Get the server URL for single frame */
  getFrameUrl(): string
  /** Get the server URL for H.264 WebSocket streaming */
  getH264WebsocketUrl(): string
  /** Push a JPEG frame to all connected clients */
  pushFrame(jpegData: Buffer, timestampUs: number, width: number, height: number): void
  /** Push an H.264 packet to all connected clients via WebSocket */
  pushH264Packet(data: Buffer, pts: number, dts: number, isKeyframe: boolean): void
  /** Get server statistics */
  getStats(): JsFrameServerStats
  /** Stop the server */
  stop(): void
}
/**
 * Frame server session with export support
 *
 * This server includes export API endpoints for compat mode video export:
 * - POST /export/start - Start an export job
 * - POST /export/cancel/:job_id - Cancel an export job
 * - GET /export/status/:job_id - Get export status
 * - GET /export/progress - WebSocket for real-time progress updates
 */
export declare class FrameServerWithExportSession {
  /** Start a new frame server with export support */
  static start(config?: JsFrameServerConfig | undefined | null): FrameServerWithExportSession
  /** Get the server port */
  getPort(): number
  /** Get the base URL for the server */
  getBaseUrl(): string
  /** Get the server URL for MJPEG streaming */
  getMjpegUrl(): string
  /** Get the server URL for WebSocket streaming */
  getWebsocketUrl(): string
  /** Get the export API base URL */
  getExportUrl(): string
  /** Get the server URL for H.264 WebSocket streaming */
  getH264WebsocketUrl(): string
  /** Push a JPEG frame to all connected clients */
  pushFrame(jpegData: Buffer, timestampUs: number, width: number, height: number): void
  /** Push an H.264 packet to all connected clients via WebSocket */
  pushH264Packet(data: Buffer, pts: number, dts: number, isKeyframe: boolean): void
  /** Get server statistics */
  getStats(): JsFrameServerStats
  /** Stop the server */
  stop(): void
}
/** Stateful muxer session for container output */
export declare class MuxerSession {
  /** Create a new muxer session */
  static create(config: JsMuxerConfig): MuxerSession
  /** Add a video stream to the output */
  addVideoStream(config: JsEncoderConfig): JsStreamInfo
  /** Add an audio stream to the output */
  addAudioStream(config: JsAudioEncoderConfig): JsStreamInfo
  /** Write the container header (must be called after adding all streams) */
  writeHeader(): void
  /** Write a video packet */
  writeVideoPacket(packet: JsMuxerPacket): void
  /** Write an audio packet */
  writeAudioPacket(packet: JsMuxerPacket): void
  /** Finish muxing and close the file */
  finish(): void
  /** Check if muxer is open */
  isOpen(): boolean
}
/**
 * Async export pipeline session for high-performance video export
 *
 * This implements a three-stage concurrent pipeline:
 * - Compose (GPU): Composites layers into frames
 * - Encode (CPU/HW): Encodes frames to video codec
 * - Mux (IO): Writes encoded packets to container file
 *
 * Usage:
 * ```javascript
 * const pipeline = await ExportPipelineSession.create({
 *     outputPath: '/path/to/output.mp4',
 *     encoderConfig: { width: 1920, height: 1080, fps: 30, codec: 'h264', hwEncoder: 'auto' },
 *     totalFrames: 300
 * });
 *
 * for (let i = 0; i < 300; i++) {
 *     pipeline.submitFrame({ index: i, pts: i * 1001, layers: [...], outputWidth: 1920, outputHeight: 1080 });
 *     const progress = pipeline.getProgress();
 *     console.log(`Progress: ${progress.progressRatio * 100}%`);
 * }
 *
 * await pipeline.finalize();
 * ```
 */
export declare class ExportPipelineSession {
  /** Create a new export pipeline session */
  static create(config: JsPipelineConfig): Promise<ExportPipelineSession>
  /**
   * Submit a frame to the pipeline for processing
   *
   * This may block if the compose buffer is full (backpressure).
   * The frame will be processed asynchronously through the pipeline.
   */
  submitFrame(frame: JsPipelineFrame): void
  /** Get current pipeline progress */
  getProgress(): JsPipelineProgress
  /** Check if pipeline is cancelled */
  isCancelled(): boolean
  /**
   * Cancel the pipeline
   *
   * This signals all workers to stop. The output file may be incomplete or corrupted.
   */
  cancel(): void
  /**
   * Finalize the pipeline and wait for completion
   *
   * This signals that no more frames will be submitted and waits for all
   * pending frames to be processed and written to the output file.
   *
   * After this call, the session cannot be used again.
   */
  finalize(): Promise<void>
}
/**
 * Preview Pipeline Session - Zero-copy GPU pipeline for real-time H.264 preview
 *
 * Data flow (macOS):
 * ```text
 * Timeline → GpuExportPipeline (decode + composite + IOSurface)
 *         → VideoToolbox H.264 Encode → H.264 NAL units
 * ```
 *
 * All processing stays on GPU until final H.264 output.
 */
export declare class PreviewPipelineSession {
  /** Create a new preview pipeline from timeline JSON */
  static create(timelineJson: string, config: JsPreviewPipelineConfig): PreviewPipelineSession
  /**
   * Render frame at given time and encode to H.264
   *
   * Returns H.264 NAL units ready for WebSocket streaming.
   */
  renderFrame(time: number, backgroundColor?: Array<number> | undefined | null): Array<JsPreviewFrame>
  /** Flush encoder and get remaining packets */
  flush(): Array<JsPreviewFrame>
  /** Reset frame counter (call on seek) */
  resetFrameCounter(): void
  /** Check if hardware encoding is active */
  isHwActive(): boolean
  /** Get current configuration */
  getConfig(): JsPreviewPipelineConfig
  /** Close the pipeline and release resources */
  close(): void
}
