/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'neko-engine.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.android-arm64.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'neko-engine.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.android-arm-eabi.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'neko-engine.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'neko-engine.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'neko-engine.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'neko-engine.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./neko-engine.darwin-universal.node')
      } else {
        nativeBinding = require('@neko-engine/native-napi-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'neko-engine.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.darwin-x64.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'neko-engine.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.darwin-arm64.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'neko-engine.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./neko-engine.freebsd-x64.node')
      } else {
        nativeBinding = require('@neko-engine/native-napi-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-x64-musl.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'neko-engine.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./neko-engine.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@neko-engine/native-napi-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'neko-engine.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./neko-engine.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@neko-engine/native-napi-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { MediaProcessor, VideoEncoderSession, AudioDecoderSession, AudioEncoderSession, MuxerSession, CompositorSession, AnimationSession, createFadeInAnimation, createFadeOutAnimation, createSlideInLeftAnimation, createZoomInAnimation, createBounceAnimation, createPulseAnimation, ExportPipelineSession, FrameServerSession, FrameServerWithExportSession, probeMedia, extractAllSubtitles, encodeJpeg, FrameFormat, extractFrame, compositeFrame, JsTextureFormat, JsVideoCodec, JsContainerFormat, JsEncoderPreset, JsAudioCodec, JsSampleFormat, JsBlendMode, JsEasingType, JsInterpolationMode } = nativeBinding

module.exports.MediaProcessor = MediaProcessor
module.exports.VideoEncoderSession = VideoEncoderSession
module.exports.AudioDecoderSession = AudioDecoderSession
module.exports.AudioEncoderSession = AudioEncoderSession
module.exports.MuxerSession = MuxerSession
module.exports.CompositorSession = CompositorSession
module.exports.AnimationSession = AnimationSession
module.exports.createFadeInAnimation = createFadeInAnimation
module.exports.createFadeOutAnimation = createFadeOutAnimation
module.exports.createSlideInLeftAnimation = createSlideInLeftAnimation
module.exports.createZoomInAnimation = createZoomInAnimation
module.exports.createBounceAnimation = createBounceAnimation
module.exports.createPulseAnimation = createPulseAnimation
module.exports.ExportPipelineSession = ExportPipelineSession
module.exports.FrameServerSession = FrameServerSession
module.exports.FrameServerWithExportSession = FrameServerWithExportSession
module.exports.probeMedia = probeMedia
module.exports.extractAllSubtitles = extractAllSubtitles
module.exports.encodeJpeg = encodeJpeg
module.exports.FrameFormat = FrameFormat
module.exports.extractFrame = extractFrame
module.exports.compositeFrame = compositeFrame
module.exports.JsTextureFormat = JsTextureFormat
module.exports.JsVideoCodec = JsVideoCodec
module.exports.JsContainerFormat = JsContainerFormat
module.exports.JsEncoderPreset = JsEncoderPreset
module.exports.JsAudioCodec = JsAudioCodec
module.exports.JsSampleFormat = JsSampleFormat
module.exports.JsBlendMode = JsBlendMode
module.exports.JsEasingType = JsEasingType
module.exports.JsInterpolationMode = JsInterpolationMode
