import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { GeneratedAsset } from '@neko/shared';
import { GeneratedOutputLifecycleService } from '../generated-output-lifecycle';

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    temporaryDirectories
      .splice(0)
      .map((directory) => fs.rm(directory, { recursive: true, force: true })),
  );
});

describe('GeneratedOutputLifecycleService', () => {
  it('fails closed when references cannot be proven', async () => {
    const { service, filePath, remove } = await createFixture();

    await expect(service.delete('generated-1')).resolves.toMatchObject({
      status: 'rejected',
      code: 'reference-check-unavailable',
    });
    expect(remove).not.toHaveBeenCalled();
    await expect(fs.access(filePath)).resolves.toBeUndefined();
  });

  it('retains files still referenced by a project', async () => {
    const { service, filePath, remove } = await createFixture();

    await expect(
      service.delete('generated-1', {
        findReferences: vi.fn().mockResolvedValue(['neko/boards/workspace.nkc#media-1']),
      }),
    ).resolves.toMatchObject({
      status: 'rejected',
      code: 'generated-output-referenced',
      references: ['neko/boards/workspace.nkc#media-1'],
    });
    expect(remove).not.toHaveBeenCalled();
    await expect(fs.access(filePath)).resolves.toBeUndefined();
  });

  it('deletes only an unreferenced canonical generated file', async () => {
    const { service, filePath, remove } = await createFixture();

    await expect(
      service.delete('generated-1', { findReferences: vi.fn().mockResolvedValue([]) }),
    ).resolves.toEqual({ status: 'deleted', assetId: 'generated-1', fileMissing: false });
    expect(remove).toHaveBeenCalledWith('generated-1');
    await expect(fs.access(filePath)).rejects.toThrow();
  });

  it('rejects indexed files outside the canonical generated root', async () => {
    const root = await createTemporaryDirectory();
    const asset = createAsset(path.join(root, 'outside.png'));
    const service = new GeneratedOutputLifecycleService(root, {
      get: () => asset,
      add: vi.fn(),
      remove: vi.fn(),
    });

    await expect(
      service.delete('generated-1', { findReferences: vi.fn().mockResolvedValue([]) }),
    ).resolves.toMatchObject({ status: 'rejected', code: 'generated-output-path-invalid' });
  });
});

async function createFixture() {
  const root = await createTemporaryDirectory();
  const filePath = path.join(root, 'neko', 'generated', 'image', 'generated-1.png');
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, 'generated bytes');
  const asset = createAsset(filePath);
  const remove = vi.fn().mockResolvedValue(true);
  const service = new GeneratedOutputLifecycleService(root, {
    get: () => asset,
    add: vi.fn(),
    remove,
  });
  return { service, filePath, remove };
}

function createAsset(filePath: string): GeneratedAsset {
  return {
    id: 'generated-1',
    type: 'generated-image',
    path: filePath,
    mimeType: 'image/png',
    generatedAt: '2026-07-15T00:00:00.000Z',
    width: 1024,
    height: 1024,
    ratio: '1:1',
  };
}

async function createTemporaryDirectory(): Promise<string> {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'neko-output-lifecycle-'));
  temporaryDirectories.push(directory);
  return directory;
}
