/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Probe media file metadata via the unified API
 *
 * Maps to: videos:probe
 *
 * Returns JSON ActionResponse with media metadata (streams, duration, format, etc.)
 */
export declare function bridgeProbeMedia(path: string): Promise<string>
/**
 * Extract all subtitle tracks from a media file via the unified API
 *
 * Maps to: videos:extract (type=subtitles)
 *
 * Returns JSON ActionResponse with extracted subtitle tracks
 */
export declare function bridgeExtractSubtitles(path: string): Promise<string>
/**
 * Extract a single frame from video via the unified API
 *
 * Maps to: videos:capture
 *
 * Returns JSON ActionResponse with base64-encoded frame data
 */
export declare function bridgeExtractFrame(path: string, time: number, quality?: number | undefined | null, width?: number | undefined | null, height?: number | undefined | null): Promise<string>
/**
 * Get GPU information via the unified API
 *
 * Maps to: nodes:gpu
 *
 * Returns JSON ActionResponse with GPU device info
 */
export declare function bridgeGpuInfo(): Promise<string>
/**
 * Get audio file information via the unified API
 *
 * Maps to: audios:probe
 *
 * Returns JSON ActionResponse with audio metadata (codec, sample rate, channels, etc.)
 */
export declare function bridgeAudioInfo(path: string): Promise<string>
/**
 * Generate waveform data for a media file via the unified API
 *
 * Maps to: videos:waveform
 *
 * Returns JSON ActionResponse with waveform sample data
 */
export declare function bridgeGenerateWaveform(path: string): Promise<string>
/**
 * Get keyframe timestamps from a video file via the unified API
 *
 * Maps to: videos:keyframes
 *
 * Returns JSON ActionResponse with keyframe timestamp list
 */
export declare function bridgeGetKeyframes(path: string): Promise<string>
/**
 * List available shader effects via the unified API
 *
 * Maps to: effects:list
 *
 * Returns JSON ActionResponse with available preset and custom shaders
 */
export declare function bridgeEffectsList(): Promise<string>
/**
 * Get shader info via the unified API
 *
 * Maps to: effects:info
 *
 * Returns JSON ActionResponse with shader parameter definitions
 */
export declare function bridgeEffectsInfo(shaderId: string): Promise<string>
/**
 * Apply a shader effect to RGBA frame data via the unified API
 *
 * Maps to: effects:apply
 *
 * Returns JSON ActionResponse with processed base64-encoded RGBA data
 */
export declare function bridgeEffectsApply(dataBase64: string, width: number, height: number, shaderId: string, paramsJson?: string | undefined | null): Promise<string>
/**
 * Register a custom WGSL shader via the unified API
 *
 * Maps to: effects:register
 *
 * Returns JSON ActionResponse confirming registration
 */
export declare function bridgeEffectsRegister(id: string, code: string, paramsJson?: string | undefined | null): Promise<string>
/**
 * Encode RGBA pixel data to JPEG via the unified API
 *
 * Maps to: images:encode
 *
 * Returns JSON ActionResponse with base64-encoded JPEG data
 */
export declare function bridgeEncodeJpeg(rgbaDataBase64: string, width: number, height: number, quality?: number | undefined | null): Promise<string>
/** GPU information for JavaScript */
export interface JsGpuInfo {
  name: string
  vendor: string
  backend: string
  deviceType: string
}
/** Frame data for JavaScript */
export interface JsFrameData {
  width: number
  height: number
  format: string
  data: Buffer
  timestamp: number
  isKeyframe: boolean
}
/** Hardware acceleration info for JavaScript */
export interface JsHwAccelInfo {
  decoders: Array<string>
  encoders: Array<string>
  recommendedDecoder: string
  recommendedEncoder: string
}
/** Audio info for JavaScript */
export interface JsAudioInfo {
  sampleRate: number
  channels: number
  duration: number
  codec: string
  bitrate: number
  totalSamples: number
}
/** Probed media information for JavaScript */
export interface JsProbeMediaInfo {
  duration: number
  width: number
  height: number
  fps: number
  codec: string
  format: string
  bitrate?: number
  hasAudio: boolean
  audioCodec?: string
  audioSampleRate?: number
  audioChannels?: number
  audioBitrate?: number
  hasSubtitles: boolean
  subtitleStreams: Array<JsProbeSubtitleStream>
}
/** Subtitle stream info for JavaScript */
export interface JsProbeSubtitleStream {
  index: number
  codec: string
  language?: string
  title?: string
  isDefault: boolean
  isForced: boolean
}
/** Subtitle cue for JavaScript */
export interface JsSubtitleCue {
  id: string
  startTime: number
  endTime: number
  text: string
}
/** Extracted subtitle track for JavaScript */
export interface JsExtractedSubtitleTrack {
  streamIndex: number
  language?: string
  title?: string
  isDefault: boolean
  cues: Array<JsSubtitleCue>
}
/**
 * NativeEngine - Main entry point for all engine operations
 *
 * This class provides a unified interface to the Neko Engine through
 * the ActionRequest/ActionResponse protocol.
 *
 * It also manages an optional embedded HTTP/WebSocket server for
 * per-stream frame delivery to webview consumers.
 */
export declare class NativeEngine {
  /**
   * Create a new NativeEngine instance
   *
   * @param config_path - Optional path to engine.toml config file.
   *   If omitted, loads from ~/.neko/engine.toml and .neko/engine.toml.
   */
  static create(configPath?: string | undefined | null): Promise<NativeEngine>
  /**
   * Dispatch an action request
   *
   * This is the main entry point for all operations.
   * Takes a JSON string representing an ActionRequest and returns
   * a JSON string representing an ActionResponse.
   */
  dispatch(requestJson: string): Promise<string>
  /**
   * Dispatch an action request with typed parameters
   *
   * Convenience method that takes individual parameters instead of JSON.
   * All ActionRequest fields are supported for full parity with `dispatch()`.
   */
  dispatchAction(group: string, action: string, id?: string | undefined | null, options?: string | undefined | null, source?: string | undefined | null, sessionId?: string | undefined | null, streamId?: string | undefined | null, body?: string | undefined | null): Promise<string>
  /** Check if GPU is available */
  hasGpu(): boolean
  /** Get list of supported action groups */
  groups(): Array<string>
  /** Get list of supported actions for a group */
  actions(group: string): Array<string> | null
  /** Get system health status */
  health(): Promise<string>
  /** Get system metrics (CPU, memory, GPU usage) */
  metrics(): Promise<string>
  /** Get GPU information */
  gpuInfo(): Promise<string>
  /** Probe a video file for metadata */
  probeVideo(source: string): Promise<string>
  /** List all active tasks */
  listTasks(): Promise<string>
  /** Get task progress */
  getTaskProgress(taskId: string): Promise<string>
  /** Cancel a task */
  cancelTask(taskId: string): Promise<string>
  /**
   * Capture a single frame from video
   *
   * Returns JSON with base64-encoded frame data
   */
  captureFrame(source: string, time: number, quality?: number | undefined | null, format?: string | undefined | null): Promise<string>
  /**
   * Start the embedded HTTP/WebSocket server (full neko-host-http router).
   *
   * The server provides:
   * - `ws://127.0.0.1:{port}/v1/streams/{stream_id}` — per-stream WebSocket
   * - `POST http://127.0.0.1:{port}/v1/dispatch` — ActionRequest dispatch
   * - `GET http://127.0.0.1:{port}/health` — health check
   * - `POST http://127.0.0.1:{port}/v1/preview/register` — register file for Range serving
   * - `GET http://127.0.0.1:{port}/v1/preview/file/:token` — serve file with Range support
   *
   * Returns the actual bound port (useful when port=0 for auto-assign).
   */
  startFrameServer(port?: number | undefined | null): Promise<number>
  /** Start the embedded HTTP/WebSocket server with preview file allow-list roots. */
  startFrameServerWithPreviewRoots(port?: number | undefined | null, previewAllowedRoots?: Array<string> | undefined | null): Promise<number>
  /**
   * Update preview/file access allow-list roots for the running engine.
   *
   * The HTTP router and JSON controllers share the same EngineApi-backed
   * registry, so this can safely be called after the frame server has
   * already started.
   */
  setPreviewAllowedRoots(previewAllowedRoots?: Array<string> | undefined | null): void
  /** Stop the embedded HTTP/WebSocket server */
  stopFrameServer(): Promise<void>
  /** Get the frame server port, or null if not running */
  getFrameServerPort(): number | null
}
