import { describe, expect, it, vi } from 'vitest';
import {
  CANVAS_BOARD_ROUTING_CONTRACT_VERSION,
  CANVAS_GENERATED_DRAFT_GROUP_CONTRACT_VERSION,
  createGeneratedAssetRevisionRef,
  type CanvasBoardDeliveryRequest,
  type GeneratedAssetRevisionRef,
} from '@neko/shared';
import { CanvasGeneratedDraftProjectionService } from './canvasGeneratedDraftProjectionService';

describe('CanvasGeneratedDraftProjectionService', () => {
  it('groups one task run, pins candidates, and never projects Host source paths', async () => {
    const first = lifecycle('generated-output:1', 'sha256:first');
    const second = lifecycle('generated-output:2', 'sha256:second');
    const publish = vi.fn(async () => true);
    const setReviewPin = vi.fn(async () => undefined);
    const service = new CanvasGeneratedDraftProjectionService({
      lifecycle: {
        resolve: vi.fn(async (resourceRef) => {
          const item = resourceRef.id === first.resourceRef.id ? first : second;
          return {
            status: 'ready' as const,
            assetId: item.assetId,
            revision: item.revision,
            contentDigest: item.contentDigest,
            mediaKind: item.mediaKind,
            mimeType: item.mimeType,
            taskId: item.generation.taskId,
            runId: item.generation.runId,
            sourcePath: `/workspace/.neko/.cache/generated/image/${item.assetId}.png`,
          };
        }),
        setReviewPin,
      },
      publisher: { publish, remove: vi.fn(async () => true) },
      now: () => '2026-07-15T01:02:00.000Z',
    });

    const firstProjection = await service.upsertFromBoardDelivery(request(first, 'First'));
    const secondProjection = await service.upsertFromBoardDelivery(request(second, 'Second'));
    const replayed = await service.upsertFromBoardDelivery(request(first, 'First'));

    expect(firstProjection.candidates).toHaveLength(1);
    expect(secondProjection.candidates).toHaveLength(2);
    expect(replayed.candidates).toHaveLength(2);
    expect(new Set(replayed.candidates.map((candidate) => candidate.candidateId)).size).toBe(2);
    expect(setReviewPin).toHaveBeenCalledWith(first.resourceRef, {
      pinned: true,
      ownerId: replayed.projectionId,
    });
    expect(JSON.stringify(publish.mock.calls)).not.toContain('/workspace/');
    expect(
      service.getResolvedSources(replayed.projectionId, [replayed.candidates[0]!.candidateId]),
    ).toEqual([expect.objectContaining({ sourcePath: expect.stringContaining('/workspace/') })]);

    const candidateIds = replayed.candidates.map((candidate) => candidate.candidateId);
    await service.beginPromotion(replayed.projectionId, candidateIds);
    await service.applyPromotionResult({
      version: CANVAS_GENERATED_DRAFT_GROUP_CONTRACT_VERSION,
      requestId: 'promotion:partial',
      projectionId: replayed.projectionId,
      status: 'partial',
      items: [
        {
          candidateId: candidateIds[0]!,
          status: 'saved',
          asset: {
            entityId: 'asset:entity:1',
            variantId: 'asset:variant:1',
            fileId: 'asset:file:1',
            path: 'neko/assets/files/image/first.png',
            mediaType: 'image',
          },
        },
        {
          candidateId: candidateIds[1]!,
          status: 'failed',
          diagnostic: {
            code: 'asset-storage-failed',
            severity: 'error',
            message: 'Second candidate failed.',
          },
        },
      ],
    });
    expect(service.get(replayed.projectionId)?.candidates).toEqual([
      expect.objectContaining({
        state: 'saved-to-assets',
        promotedAsset: expect.objectContaining({ entityId: 'asset:entity:1' }),
      }),
      expect.objectContaining({ state: 'failed', diagnostic: 'Second candidate failed.' }),
    ]);
  });

  it('shows fail-visible unavailable state when runtime bytes cannot be reconstructed', async () => {
    const item = lifecycle('generated-output:1', 'sha256:first');
    const service = new CanvasGeneratedDraftProjectionService({
      lifecycle: {
        resolve: vi.fn(async () => ({
          status: 'unavailable' as const,
          diagnostic: 'Generated bytes were reclaimed.',
        })),
        setReviewPin: vi.fn(async () => undefined),
      },
      publisher: { publish: vi.fn(async () => true), remove: vi.fn(async () => true) },
    });

    const projection = await service.upsertFromBoardDelivery(request(item, 'Missing'));

    expect(projection.candidates).toEqual([
      expect.objectContaining({
        state: 'unavailable',
        diagnostic: 'Generated bytes were reclaimed.',
      }),
    ]);
    expect(() =>
      service.getResolvedSources(projection.projectionId, [projection.candidates[0]!.candidateId]),
    ).toThrow(/source unavailable/);
  });

  it('requires explicit discard before unpinning unsaved candidates', async () => {
    const item = lifecycle('generated-output:1', 'sha256:first');
    const setReviewPin = vi.fn(async () => undefined);
    const remove = vi.fn(async () => true);
    const service = new CanvasGeneratedDraftProjectionService({
      lifecycle: {
        resolve: vi.fn(async () => ({
          status: 'ready' as const,
          assetId: item.assetId,
          revision: item.revision,
          contentDigest: item.contentDigest,
          mediaKind: item.mediaKind,
          mimeType: item.mimeType,
          taskId: item.generation.taskId,
          sourcePath: '/workspace/.neko/.cache/generated/image/candidate.png',
        })),
        setReviewPin,
      },
      publisher: { publish: vi.fn(async () => true), remove },
    });
    const projection = await service.upsertFromBoardDelivery(request(item, 'Candidate'));

    await expect(service.disposeProjection(projection.projectionId, false)).rejects.toThrow(
      /unsaved candidates/,
    );
    await expect(service.disposeProjection(projection.projectionId, true)).resolves.toBeUndefined();
    expect(setReviewPin).toHaveBeenLastCalledWith(item.resourceRef, {
      pinned: false,
      ownerId: projection.projectionId,
    });
    expect(remove).toHaveBeenCalledWith(projection.projectionId, 'neko/boards/story.nkc');
  });

  it('rejects discard while candidate promotion is in progress', async () => {
    const item = lifecycle('generated-output:1', 'sha256:first');
    const service = new CanvasGeneratedDraftProjectionService({
      lifecycle: {
        resolve: vi.fn(async () => ({
          status: 'ready' as const,
          assetId: item.assetId,
          revision: item.revision,
          contentDigest: item.contentDigest,
          mediaKind: item.mediaKind,
          mimeType: item.mimeType,
          taskId: item.generation.taskId,
          sourcePath: '/workspace/.neko/.cache/generated/image/candidate.png',
        })),
        setReviewPin: vi.fn(async () => undefined),
      },
      publisher: {
        publish: vi.fn(async () => true),
        remove: vi.fn(async () => true),
      },
    });
    const projection = await service.upsertFromBoardDelivery(request(item, 'Candidate'));
    const candidateId = projection.candidates[0]!.candidateId;
    await service.beginPromotion(projection.projectionId, [candidateId]);

    await expect(service.disposeProjection(projection.projectionId, true)).rejects.toThrow(
      /promotion is in progress/i,
    );
    expect(service.get(projection.projectionId)?.candidates[0]?.state).toBe('promoting');
  });
});

function lifecycle(assetId: string, contentDigest: string): GeneratedAssetRevisionRef {
  return createGeneratedAssetRevisionRef({
    assetId,
    contentDigest,
    mediaKind: 'image',
    mimeType: 'image/png',
    generation: { taskId: 'task:1', runId: 'run:1' },
  });
}

function request(item: GeneratedAssetRevisionRef, title: string): CanvasBoardDeliveryRequest {
  return {
    version: CANVAS_BOARD_ROUTING_CONTRACT_VERSION,
    target: {
      documentRef: { kind: 'workspace-path', path: 'neko/boards/story.nkc' },
      documentId: 'document:story',
      canvasId: 'canvas:story',
      revision: 'nkc:revision-1',
      conversationId: 'conversation:1',
      taskId: 'task:1',
      runId: 'run:1',
      resolutionSource: 'created',
      frozenAt: '2026-07-15T01:00:00.000Z',
    },
    provenance: {
      version: CANVAS_BOARD_ROUTING_CONTRACT_VERSION,
      deliveryId: `delivery:${item.assetId}`,
      artifactId: `${item.assetId}:${item.revision}`,
      kind: 'image',
      conversationId: 'conversation:1',
      taskId: 'task:1',
      runId: 'run:1',
      sourceId: 'assistant:1',
      createdAt: '2026-07-15T01:00:00.000Z',
    },
    artifact: { kind: 'image', title, mimeType: 'image/png', resourceRef: item.resourceRef },
  };
}
